# Generated by Django 5.2.5 on 2025-08-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMaster',
            fields=[
                ('profile_id', models.AutoField(db_column='ProfileID', primary_key=True, serialize=False)),
                ('profile_name', models.CharField(db_column='ProfileName', max_length=100)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ProfileMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('user_code', models.CharField(db_column='UserCode', max_length=20, unique=True)),
                ('user_name', models.CharField(db_column='UserName', max_length=100)),
                ('password_hash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('school_id', models.IntegerField(blank=True, db_column='SchoolID', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'UserMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_identifier', models.CharField(db_column='LoginIdentifier', max_length=256)),
                ('profile_id', models.IntegerField(blank=True, db_column='ProfileId', null=True)),
                ('profile_name', models.CharField(blank=True, db_column='ProfileName', max_length=200, null=True)),
                ('school_id', models.IntegerField(blank=True, db_column='SchoolId', null=True)),
                ('school_name', models.CharField(blank=True, db_column='SchoolName', max_length=200, null=True)),
                ('otp_hash', models.CharField(db_column='OTPHash', max_length=128)),
                ('sent_via', models.CharField(db_column='SentVia', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('expires_at', models.DateTimeField(blank=True, db_column='ExpiresAt', null=True)),
                ('is_used', models.BooleanField(db_column='IsUsed', default=False)),
                ('attempt_count', models.IntegerField(db_column='AttemptCount', default=0)),
                ('request_ip', models.CharField(blank=True, db_column='RequestIP', max_length=50, null=True)),
                ('device_info', models.CharField(blank=True, db_column='DeviceInfo', max_length=500, null=True)),
            ],
            options={
                'db_table': 'UserOTP',
                'managed': False,
            },
        ),
    ]
