# Generated by Django 5.2.5 on 2025-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('ip_address', models.CharField(max_length=45, null=True)),
                ('device_info', models.TextField(null=True)),
            ],
            options={
                'db_table': 'OTPRecords',
                'managed': False,
            },
        ),
    ]
