# Generated by Django 5.2.5 on 2025-08-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classsubject_student_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumaster',
            options={'managed': False},
        ),
    ]
