# Generated by Django 5.2.5 on 2025-08-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_menumaster_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassSubject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
