# Generated by Django 5.2.5 on 2025-08-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_classsubject_delete_student_delete_teacher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeographicalMaster',
        ),
    ]
