# Generated by Django 5.2.5 on 2025-08-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fee_management_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('payment_id', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(db_column='StudentID')),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(db_column='PaymentMode', max_length=50)),
                ('transaction_ref', models.CharField(blank=True, db_column='TransactionRef', max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_column='PaymentDate')),
                ('receipt_number', models.CharField(db_column='ReceiptNumber', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'FeePayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('fee_id', models.AutoField(db_column='FeeID', primary_key=True, serialize=False)),
                ('class_id', models.IntegerField(db_column='ClassID')),
                ('fee_type', models.CharField(db_column='FeeType', max_length=50)),
                ('fee_name', models.CharField(db_column='FeeName', max_length=100)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('is_mandatory', models.BooleanField(db_column='IsMandatory', default=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'FeeStructure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('receipt_id', models.AutoField(db_column='ReceiptID', primary_key=True, serialize=False)),
                ('receipt_type', models.CharField(db_column='ReceiptType', max_length=20)),
                ('receipt_data', models.TextField(db_column='ReceiptData')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_column='GeneratedAt')),
            ],
            options={
                'db_table': 'PaymentReceipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('assignment_id', models.AutoField(db_column='AssignmentID', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(db_column='StudentID')),
                ('assigned_amount', models.DecimalField(db_column='AssignedAmount', decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, default=0, max_digits=10)),
                ('due_amount', models.DecimalField(db_column='DueAmount', decimal_places=2, max_digits=10)),
                ('status', models.CharField(db_column='Status', default='Pending', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True, db_column='AssignedDate')),
            ],
            options={
                'db_table': 'StudentFeeAssignment',
                'managed': False,
            },
        ),
    ]
