# Generated by Django 5.2.5 on 2025-08-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(db_column='StudentID')),
                ('school_id', models.IntegerField(db_column='SchoolID')),
                ('receipt_number', models.CharField(db_column='ReceiptNumber', max_length=50, unique=True)),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(db_column='PaymentMode', max_length=50)),
                ('transaction_ref', models.CharField(blank=True, db_column='TransactionRef', max_length=100, null=True)),
                ('payment_status', models.CharField(db_column='PaymentStatus', default='Completed', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_column='PaymentDate')),
                ('fee_breakdown', models.TextField(blank=True, db_column='FeeBreakdown', null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
    ]
