# Generated by Django 5.2.5 on 2025-09-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeePayment',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentReceipt',
        ),
        migrations.DeleteModel(
            name='StudentFeeAssignment',
        ),
    ]
