# Generated by Django 5.2.5 on 2025-09-14 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_facetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('email_tracking_id', models.AutoField(db_column='EmailTrackingID', primary_key=True, serialize=False)),
                ('email_code', models.CharField(db_column='EmailCode', max_length=100)),
                ('to_email', models.EmailField(db_column='ToEmail', max_length=255)),
                ('from_email', models.EmailField(blank=True, db_column='FromEmail', max_length=255, null=True)),
                ('subject', models.CharField(blank=True, db_column='Subject', max_length=500, null=True)),
                ('school_id', models.IntegerField(blank=True, db_column='SchoolID', null=True)),
                ('email_body', models.TextField(blank=True, db_column='EmailBody', null=True)),
                ('email_html_body', models.TextField(blank=True, db_column='EmailHtmlBody', null=True)),
                ('placeholders', models.TextField(blank=True, db_column='Placeholders', null=True)),
                ('has_attachments', models.BooleanField(db_column='HasAttachments', default=False)),
                ('attachment_count', models.IntegerField(db_column='AttachmentCount', default=0)),
                ('attachment_details', models.TextField(blank=True, db_column='AttachmentDetails', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('PermanentlyFailed', 'Permanently Failed')], db_column='Status', default='Pending', max_length=50)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium-High'), (4, 'Medium'), (5, 'Normal'), (6, 'Low-Medium'), (7, 'Low'), (8, 'Very Low'), (9, 'Minimal'), (10, 'Background')], db_column='Priority', default=5)),
                ('attempt_count', models.IntegerField(db_column='AttemptCount', default=0)),
                ('max_attempts', models.IntegerField(db_column='MaxAttempts', default=3)),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now)),
                ('scheduled_at', models.DateTimeField(db_column='ScheduledAt', default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, db_column='StartedAt', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_column='CompletedAt', null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_column='NextRetryAt', null=True)),
                ('last_error', models.TextField(blank=True, db_column='LastError', null=True)),
                ('error_details', models.TextField(blank=True, db_column='ErrorDetails', null=True)),
                ('user_id', models.IntegerField(blank=True, db_column='UserID', null=True)),
                ('session_id', models.CharField(blank=True, db_column='SessionID', max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, db_column='RequestID', max_length=255, null=True)),
                ('student_code', models.CharField(blank=True, db_column='StudentCode', max_length=50, null=True)),
                ('receipt_number', models.CharField(blank=True, db_column='ReceiptNumber', max_length=50, null=True)),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'EmailTracking',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
