# Generated by Django 5.2.5 on 2025-09-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_emailtracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponentMaster',
            fields=[
                ('component_id', models.AutoField(db_column='ComponentID', primary_key=True, serialize=False)),
                ('component_name', models.CharField(db_column='ComponentName', max_length=100)),
                ('component_type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], db_column='ComponentType', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'SalaryComponentMaster',
                'managed': False,
            },
        ),
    ]
