# Generated by Django 5.2.5 on 2025-09-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_create_salary_component_data'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Insert salary components for all schools (1, 2, 3)
            -- Only insert if they don't already exist for each school
            
            -- School 1 (Gyan Nikeetan Middle School)
            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'Basic Salary', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'Basic Salary');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'House Rent Allowance (HRA)', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'House Rent Allowance (HRA)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'Dearness Allowance (DA)', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'Dearness Allowance (DA)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'Transport Allowance', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'Transport Allowance');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'Medical Allowance', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'Medical Allowance');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'Special Allowance', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'Special Allowance');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'Provident Fund (PF)', 'Deduction', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'Provident Fund (PF)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'Professional Tax (PT)', 'Deduction', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'Professional Tax (PT)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'Income Tax (TDS)', 'Deduction', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'Income Tax (TDS)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 1, 'Other Deductions', 'Deduction', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 1 AND "ComponentName" = 'Other Deductions');
            
            -- School 2 (Sanskar Bharti Public School)
            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'Basic Salary', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'Basic Salary');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'House Rent Allowance (HRA)', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'House Rent Allowance (HRA)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'Dearness Allowance (DA)', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'Dearness Allowance (DA)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'Transport Allowance', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'Transport Allowance');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'Medical Allowance', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'Medical Allowance');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'Special Allowance', 'Earning', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'Special Allowance');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'Provident Fund (PF)', 'Deduction', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'Provident Fund (PF)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'Professional Tax (PT)', 'Deduction', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'Professional Tax (PT)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'Income Tax (TDS)', 'Deduction', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'Income Tax (TDS)');

            INSERT INTO "SalaryComponentMaster" 
            ("SchoolID", "ComponentName", "ComponentType", "CreatedBy", "CreatedAt", "IsDeleted")
            SELECT 2, 'Other Deductions', 'Deduction', 1, CURRENT_TIMESTAMP, false
            WHERE NOT EXISTS (SELECT 1 FROM "SalaryComponentMaster" WHERE "SchoolID" = 2 AND "ComponentName" = 'Other Deductions');

            -- School 3 (PMP Public School) - already has data from previous migration
            -- No need to insert again
            """,
            reverse_sql="""
            DELETE FROM "SalaryComponentMaster" WHERE "SchoolID" IN (1, 2);
            """
        ),
    ]
