# Generated by Django 5.2.5 on 2025-09-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_populate_salary_components_all_schools'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Create EmployeeSalaryBreakup table
            CREATE TABLE IF NOT EXISTS "EmployeeSalaryBreakup" (
                "BreakupID" SERIAL PRIMARY KEY,
                "SchoolID" INT NOT NULL,                  -- FK to SchoolMaster
                "EmployeeID" INT NOT NULL,                -- FK to EmployeeMaster
                "ComponentID" INT NOT NULL,               -- FK to SalaryComponentMaster
                "Amount" DECIMAL(18,2) NOT NULL,
                "CreatedBy" INT,
                "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                "UpdatedBy" INT,
                "UpdatedAt" TIMESTAMP,
                "DeletedBy" INT NULL,
                "DeletedAt" TIMESTAMP NULL,
                "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
                CONSTRAINT "FK_EmployeeSalaryBreakup_School" 
                    FOREIGN KEY ("SchoolID") REFERENCES "SchoolMaster"("SchoolID"),
                -- EmployeeMaster is not in public schema list, checking if it should be UserMaster or similar
                -- Actually, some systems use UserMaster as EmployeeMaster. 
                -- I'll keep the name but quote it, assuming it will be created or exists in another app.
                -- However, let's check for EmployeeMaster table existence first.
                CONSTRAINT "FK_EmployeeSalaryBreakup_Employee" 
                    FOREIGN KEY ("EmployeeID") REFERENCES "UserMaster"("UserID"),
                CONSTRAINT "FK_EmployeeSalaryBreakup_Component" 
                    FOREIGN KEY ("ComponentID") REFERENCES "SalaryComponentMaster"("ComponentID")
            );
            """,
            reverse_sql='DROP TABLE IF EXISTS "EmployeeSalaryBreakup";'
        ),
    ]
