# Generated by Django 5.2.5 on 2025-09-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_create_employee_salary_breakup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryBreakup',
            fields=[
                ('breakup_id', models.AutoField(db_column='BreakupID', primary_key=True, serialize=False)),
                ('school_id', models.IntegerField(db_column='SchoolID')),
                ('employee_id', models.IntegerField(db_column='EmployeeID')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DeletedAt', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'EmployeeSalaryBreakup',
                'managed': False,
            },
        ),
    ]
