# Generated by Django 5.2.5 on 2025-09-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_employeesalarybreakup'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            DECLARE
                v_TeachersStaffMenuID INT;
            BEGIN
                -- First, check if 'Teachers & Staff' parent menu exists, if not create it
                PERFORM 1 FROM "MenuMaster" WHERE "MenuName" = 'Teachers & Staff' AND "IsDeleted" IS FALSE;
                IF NOT FOUND THEN
                    INSERT INTO "MenuMaster" 
                    ("MenuName", "DisplayOrder", "ParentMenuID", "MenuURL", "Icon", "IsActive", "CreatedBy", "CreatedAt", "IsDeleted")
                    VALUES
                    ('Teachers & Staff', 3, NULL, '#', 'fas fa-chalkboard-teacher', TRUE, 1, CURRENT_TIMESTAMP, FALSE);
                END IF;
                
                -- Get the MenuID of 'Teachers & Staff' parent menu
                SELECT "MenuID" INTO v_TeachersStaffMenuID FROM "MenuMaster" WHERE "MenuName" = 'Teachers & Staff' AND "IsDeleted" IS FALSE;
                
                -- Insert 'View Assign Class' menu item as child of 'Teachers & Staff'
                PERFORM 1 FROM "MenuMaster" WHERE "MenuName" = 'View Assign Class' AND "IsDeleted" IS FALSE;
                IF NOT FOUND THEN
                    INSERT INTO "MenuMaster" 
                    ("MenuName", "DisplayOrder", "ParentMenuID", "MenuURL", "Icon", "IsActive", "CreatedBy", "CreatedAt", "IsDeleted")
                    VALUES
                    ('View Assign Class', 1, v_TeachersStaffMenuID, '/core/staff/view-assign-class/', 'fas fa-users', TRUE, 1, CURRENT_TIMESTAMP, FALSE);
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- Remove the 'View Assign Class' menu item
            UPDATE "MenuMaster" SET "IsDeleted" = TRUE, "DeletedAt" = CURRENT_TIMESTAMP WHERE "MenuName" = 'View Assign Class';
            
            -- Note: We don't remove 'Teachers & Staff' parent menu as it might have other children
            """
        ),
    ]
