# Generated by Django 5.2.5 on 2025-09-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_view_assign_class_menu'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Update the URL for 'View Assign Class' menu item
            UPDATE MenuMaster 
            SET MenuURL = '/core/staff/view-assign-class/'
            WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """,
            reverse_sql="""
            -- Revert the URL back to original
            UPDATE MenuMaster 
            SET MenuURL = '/core/assign-classes/'
            WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """
        ),
    ]
