# Generated by Django 5.2.5 on 2025-09-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_update_view_assign_class_menu_url'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Fix the URL for 'View Assign Class' menu item (remove /core/ prefix)
            UPDATE MenuMaster 
            SET MenuURL = '/staff/view-assign-class/'
            WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """,
            reverse_sql="""
            -- Revert the URL back to previous
            UPDATE MenuMaster 
            SET MenuURL = '/core/staff/view-assign-class/'
            WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """
        ),
    ]
