# Generated by Django 5.2.5 on 2025-09-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_fix_view_assign_class_menu_url'),
    ]

    operations = [
        migrations.RunSQL(
            # Update View Assign Class menu to be under Fees parent menu
            sql="""
                UPDATE MenuMaster 
                SET ParentMenuID = 11
                WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """,
            reverse_sql="""
                UPDATE MenuMaster 
                SET ParentMenuID = 6
                WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """
        ),
    ]
