# Generated by Django 5.2.5 on 2025-09-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_move_view_assign_class_to_fees'),
    ]

    operations = [
        migrations.RunSQL(
            # Update Assign Classes menu to be under Fees parent menu
            sql="""
                UPDATE MenuMaster 
                SET ParentMenuID = 11
                WHERE MenuName = 'Assign Classes' AND IsDeleted = 0;
            """,
            reverse_sql="""
                UPDATE MenuMaster 
                SET ParentMenuID = 6
                WHERE MenuName = 'Assign Classes' AND IsDeleted = 0;
            """
        ),
    ]
