# Generated by Django 5.2.5 on 2025-09-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_move_assign_classes_to_fees'),
    ]

    operations = [
        migrations.RunSQL(
            # Move both Assign Classes and View Assign Class menus to Class parent menu
            sql="""
                UPDATE MenuMaster 
                SET ParentMenuID = 7
                WHERE MenuName IN ('Assign Classes', 'View Assign Class') 
                AND IsDeleted = 0;
            """,
            reverse_sql="""
                UPDATE MenuMaster 
                SET ParentMenuID = 11
                WHERE MenuName IN ('Assign Classes', 'View Assign Class') 
                AND IsDeleted = 0;
            """
        ),
    ]
