# Generated by Django 5.2.5 on 2025-09-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_move_assign_menus_to_class'),
    ]

    operations = [
        migrations.RunSQL(
            # Add two new menu items under Class parent menu
            sql="""
                -- Insert 'Add Class' menu item
                IF NOT EXISTS (SELECT 1 FROM MenuMaster WHERE MenuName = 'Add Class' AND IsDeleted = 0)
                BEGIN
                    INSERT INTO MenuMaster 
                    (MenuName, DisplayOrder, ParentMenuID, MenuURL, Icon, IsActive, CreatedBy, CreatedAt, IsDeleted)
                    VALUES
                    ('Add Class', 5, 7, '/core/class/add/', 'fas fa-plus', 1, 1, GETDATE(), 0);
                END
                
                -- Insert 'View Class' menu item
                IF NOT EXISTS (SELECT 1 FROM MenuMaster WHERE MenuName = 'View Class' AND IsDeleted = 0)
                BEGIN
                    INSERT INTO MenuMaster 
                    (MenuName, DisplayOrder, ParentMenuID, MenuURL, Icon, IsActive, CreatedBy, CreatedAt, IsDeleted)
                    VALUES
                    ('View Class', 6, 7, '/core/class/view/', 'fas fa-list', 1, 1, GETDATE(), 0);
                END
            """,
            reverse_sql="""
                -- Remove the added menu items
                UPDATE MenuMaster 
                SET IsDeleted = 1, UpdatedAt = GETDATE(), UpdatedBy = 1
                WHERE MenuName IN ('Add Class', 'View Class') AND IsDeleted = 0;
            """
        ),
    ]
