# Generated by Django 5.2.5 on 2025-09-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_class_menus'),
    ]

    operations = [
        migrations.RunSQL(
            # Standardize all Class menu URLs to use /core/ prefix
            sql="""
                -- Update Manage Classes URL
                UPDATE MenuMaster 
                SET MenuURL = '/core/classes/manage/'
                WHERE MenuName = 'Manage Classes' AND IsDeleted = 0;
                
                -- Update Class Reports URL
                UPDATE MenuMaster 
                SET MenuURL = '/core/classes/reports/'
                WHERE MenuName = 'Class Reports' AND IsDeleted = 0;
                
                -- Update Assign Classes URL
                UPDATE MenuMaster 
                SET MenuURL = '/core/staff/assign-classes/'
                WHERE MenuName = 'Assign Classes' AND IsDeleted = 0;
                
                -- Update View Assign Class URL
                UPDATE MenuMaster 
                SET MenuURL = '/core/staff/view-assign-class/'
                WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """,
            reverse_sql="""
                -- Revert URLs to original format
                UPDATE MenuMaster 
                SET MenuURL = '/classes/manage/'
                WHERE MenuName = 'Manage Classes' AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET MenuURL = '/classes/reports/'
                WHERE MenuName = 'Class Reports' AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET MenuURL = '/staff/assign-classes/'
                WHERE MenuName = 'Assign Classes' AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET MenuURL = '/staff/view-assign-class/'
                WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """
        ),
    ]
