# Generated by Django 5.2.5 on 2025-09-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_standardize_class_menu_urls'),
    ]

    operations = [
        migrations.RunSQL(
            # Reorganize Class menu to have only 4 items in specified order
            sql="""
                -- Remove unwanted menu items (soft delete)
                UPDATE MenuMaster 
                SET IsDeleted = 1, UpdatedAt = GETDATE(), UpdatedBy = 1
                WHERE MenuName IN ('Manage Classes', 'Class Reports') 
                AND ParentMenuID = 7 
                AND IsDeleted = 0;
                
                -- Reorder the remaining 4 menu items
                -- 1. Add Class (order 1)
                UPDATE MenuMaster 
                SET DisplayOrder = 1
                WHERE MenuName = 'Add Class' AND ParentMenuID = 7 AND IsDeleted = 0;
                
                -- 2. View Class (order 2)
                UPDATE MenuMaster 
                SET DisplayOrder = 2
                WHERE MenuName = 'View Class' AND ParentMenuID = 7 AND IsDeleted = 0;
                
                -- 3. Assign Classes (order 3)
                UPDATE MenuMaster 
                SET DisplayOrder = 3
                WHERE MenuName = 'Assign Classes' AND ParentMenuID = 7 AND IsDeleted = 0;
                
                -- 4. View Assign Class (order 4)
                UPDATE MenuMaster 
                SET DisplayOrder = 4
                WHERE MenuName = 'View Assign Class' AND ParentMenuID = 7 AND IsDeleted = 0;
            """,
            reverse_sql="""
                -- Restore the removed menu items
                UPDATE MenuMaster 
                SET IsDeleted = 0, UpdatedAt = GETDATE(), UpdatedBy = 1
                WHERE MenuName IN ('Manage Classes', 'Class Reports') 
                AND ParentMenuID = 7;
                
                -- Restore original display orders
                UPDATE MenuMaster 
                SET DisplayOrder = 1
                WHERE MenuName = 'Manage Classes' AND ParentMenuID = 7 AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET DisplayOrder = 2
                WHERE MenuName = 'Class Reports' AND ParentMenuID = 7 AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET DisplayOrder = 3
                WHERE MenuName = 'Assign Classes' AND ParentMenuID = 7 AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET DisplayOrder = 4
                WHERE MenuName = 'View Assign Class' AND ParentMenuID = 7 AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET DisplayOrder = 5
                WHERE MenuName = 'Add Class' AND ParentMenuID = 7 AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET DisplayOrder = 6
                WHERE MenuName = 'View Class' AND ParentMenuID = 7 AND IsDeleted = 0;
            """
        ),
    ]
