# Generated by Django 5.2.5 on 2025-09-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_reorganize_class_menu'),
    ]

    operations = [
        migrations.RunSQL(
            # Fix Class menu URLs to match Django URL patterns
            sql="""
                -- Fix Add Class URL
                UPDATE MenuMaster 
                SET MenuURL = '/class/add/'
                WHERE MenuName = 'Add Class' AND IsDeleted = 0;
                
                -- Fix View Class URL (temporary placeholder)
                UPDATE MenuMaster 
                SET MenuURL = '/class/view/'
                WHERE MenuName = 'View Class' AND IsDeleted = 0;
                
                -- Fix Assign Classes URL
                UPDATE MenuMaster 
                SET MenuURL = '/staff/assign-classes/'
                WHERE MenuName = 'Assign Classes' AND IsDeleted = 0;
                
                -- Fix View Assign Class URL
                UPDATE MenuMaster 
                SET MenuURL = '/staff/view-assign-class/'
                WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """,
            reverse_sql="""
                -- Revert URLs to original format
                UPDATE MenuMaster 
                SET MenuURL = '/core/class/add/'
                WHERE MenuName = 'Add Class' AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET MenuURL = '/core/class/view/'
                WHERE MenuName = 'View Class' AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET MenuURL = '/core/staff/assign-classes/'
                WHERE MenuName = 'Assign Classes' AND IsDeleted = 0;
                
                UPDATE MenuMaster 
                SET MenuURL = '/core/staff/view-assign-class/'
                WHERE MenuName = 'View Assign Class' AND IsDeleted = 0;
            """
        ),
    ]
