# Generated by Django 5.2.5 on 2025-09-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fix_class_menu_urls'),
    ]

    operations = [
        migrations.RunSQL(
            # Create Proc_Class_Set stored procedure
            sql="""
                CREATE PROCEDURE Proc_Class_Set
                    @ClassID INT = NULL,            -- NULL for Insert, ID for Update
                    @SchoolID INT,
                    @ClassName NVARCHAR(150),
                    @ClassCode NVARCHAR(50) = NULL,
                    @EducationLevel NVARCHAR(100) = NULL,
                    @Description NVARCHAR(500) = NULL,
                    @IsActive BIT = 1,
                    @UserID INT                     -- Who is performing this action
                AS
                BEGIN
                    SET NOCOUNT ON;

                    -- 🔹 Duplicate check (same School + ClassName or ClassCode)
                    IF EXISTS (
                        SELECT 1 
                        FROM ClassMaster
                        WHERE SchoolID = @SchoolID
                          AND (ClassName = @ClassName OR ClassCode = @ClassCode)
                          AND IsDeleted = 0
                          AND (@ClassID IS NULL OR ClassID <> @ClassID)  -- exclude self if updating
                    )
                    BEGIN
                        RAISERROR('Class with same name or code already exists in this school.', 16, 1);
                        RETURN;
                    END;

                    IF @ClassID IS NULL
                    BEGIN
                        -- Insert New Class
                        INSERT INTO ClassMaster
                        (
                            SchoolID, ClassName, ClassCode, EducationLevel, Description,
                            IsActive, CreatedBy, CreatedAt, IsDeleted
                        )
                        VALUES
                        (
                            @SchoolID, @ClassName, @ClassCode, @EducationLevel, @Description,
                            @IsActive, @UserID, GETDATE(), 0
                        );

                        SET @ClassID = SCOPE_IDENTITY();
                    END
                    ELSE
                    BEGIN
                        -- Update Existing Class
                        UPDATE ClassMaster
                        SET 
                            ClassName      = @ClassName,
                            ClassCode      = @ClassCode,
                            EducationLevel = @EducationLevel,
                            Description    = @Description,
                            IsActive       = @IsActive,
                            UpdatedBy      = @UserID,
                            UpdatedAt      = GETDATE()
                        WHERE ClassID = @ClassID AND IsDeleted = 0;
                    END;

                    -- Return final result
                    SELECT * FROM ClassMaster WHERE ClassID = @ClassID;
                END;
            """,
            reverse_sql="""
                -- Drop the procedure
                DROP PROCEDURE IF EXISTS Proc_Class_Set;
            """
        ),
    ]
