# Generated by Django 5.2.5 on 2025-09-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_create_proc_class_set'),
    ]

    operations = [
        migrations.RunSQL(
            # Create Proc_Section_Set stored procedure
            sql="""
                CREATE PROCEDURE Proc_Section_Set
                    @SectionID INT = NULL,          -- NULL for Insert, ID for Update
                    @ClassID INT,
                    @SectionName NVARCHAR(100),
                    @Capacity INT = NULL,
                    @RoomNumber NVARCHAR(50) = NULL,
                    @IsActive BIT = 1,
                    @UserID INT                     -- Who is performing this action
                AS
                BEGIN
                    SET NOCOUNT ON;

                    -- 🔹 Prevent duplicate Section in same Class
                    IF EXISTS (
                        SELECT 1
                        FROM SectionMaster
                        WHERE ClassID = @ClassID
                          AND SectionName = @SectionName
                          AND IsDeleted = 0
                          AND (@SectionID IS NULL OR SectionID <> @SectionID)  -- exclude self in update
                    )
                    BEGIN
                        RAISERROR('Section with same name already exists in this class.', 16, 1);
                        RETURN;
                    END;

                    IF @SectionID IS NULL
                    BEGIN
                        -- Insert New Section
                        INSERT INTO SectionMaster
                        (
                            ClassID, SectionName, Capacity, RoomNumber,
                            IsActive, CreatedBy, CreatedAt, IsDeleted
                        )
                        VALUES
                        (
                            @ClassID, @SectionName, @Capacity, @RoomNumber,
                            @IsActive, @UserID, GETDATE(), 0
                        );

                        SET @SectionID = SCOPE_IDENTITY();
                    END
                    ELSE
                    BEGIN
                        -- Update Existing Section
                        UPDATE SectionMaster
                        SET
                            SectionName = @SectionName,
                            Capacity    = @Capacity,
                            RoomNumber  = @RoomNumber,
                            IsActive    = @IsActive,
                            UpdatedBy   = @UserID,
                            UpdatedAt   = GETDATE()
                        WHERE SectionID = @SectionID AND IsDeleted = 0;
                    END;

                    -- Return final result
                    SELECT * FROM SectionMaster WHERE SectionID = @SectionID;
                END;
            """,
            reverse_sql="""
                -- Drop the procedure
                DROP PROCEDURE IF EXISTS Proc_Section_Set;
            """
        ),
    ]
