# Generated by Django 5.2.5 on 2025-09-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_create_proc_section_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMaster',
            fields=[
                ('class_id', models.AutoField(db_column='ClassID', primary_key=True, serialize=False)),
                ('class_name', models.CharField(db_column='ClassName', max_length=50)),
                ('class_code', models.CharField(db_column='ClassCode', max_length=20)),
                ('education_level', models.CharField(blank=True, db_column='EducationLevel', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'ClassMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionMaster',
            fields=[
                ('section_id', models.AutoField(db_column='SectionID', primary_key=True, serialize=False)),
                ('section_name', models.CharField(db_column='SectionName', max_length=20)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('room_number', models.CharField(blank=True, db_column='RoomNumber', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'SectionMaster',
                'managed': False,
            },
        ),
    ]
