# Generated by Django 5.2.5 on 2025-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_classmaster_sectionmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('attendance_id', models.AutoField(db_column='AttendanceID', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(db_column='StudentID')),
                ('class_id', models.IntegerField(db_column='ClassID')),
                ('section_id', models.IntegerField(blank=True, db_column='SectionID', null=True)),
                ('attendance_date', models.DateField(db_column='AttendanceDate')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Holiday', 'Holiday'), ('Late', 'Late')], db_column='Status', max_length=20)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', max_length=500, null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'db_table': 'StudentAttendance',
                'managed': False,
            },
        ),
    ]
