# Generated by Django 5.2.5 on 2025-09-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_create_student_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
