# Generated by Django 5.2.5 on 2025-09-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_delete_studentattendance'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Create FeeStructure table
            IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='FeeStructure' AND xtype='U')
            CREATE TABLE FeeStructure (
                FeeID int IDENTITY(1,1) PRIMARY KEY,
                SchoolID int NOT NULL,
                ClassID int NOT NULL,
                FeeType nvarchar(50) NOT NULL,
                FeeName nvarchar(100) NOT NULL,
                Amount decimal(10,2) NOT NULL,
                IsMandatory bit DEFAULT 1,
                IsActive bit DEFAULT 1,
                CreatedBy int NULL,
                CreatedAt datetime DEFAULT GETDATE(),
                FOREIGN KEY (SchoolID) REFERENCES SchoolMaster(SchoolID),
                FOREIGN KEY (CreatedBy) REFERENCES UserMaster(UserID)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS FeeStructure;"
        ),
        
        migrations.RunSQL(
            """
            -- Create StudentFeeAssignment table
            IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='StudentFeeAssignment' AND xtype='U')
            CREATE TABLE StudentFeeAssignment (
                AssignmentID int IDENTITY(1,1) PRIMARY KEY,
                StudentID int NOT NULL,
                FeeID int NOT NULL,
                AssignedAmount decimal(10,2) NOT NULL,
                PaidAmount decimal(10,2) DEFAULT 0,
                DueAmount decimal(10,2) NOT NULL,
                Status nvarchar(20) DEFAULT 'Pending',
                AssignedDate datetime DEFAULT GETDATE(),
                FOREIGN KEY (FeeID) REFERENCES FeeStructure(FeeID)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS StudentFeeAssignment;"
        ),
        
        migrations.RunSQL(
            """
            -- Create FeePayment table
            IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='FeePayment' AND xtype='U')
            CREATE TABLE FeePayment (
                PaymentID int IDENTITY(1,1) PRIMARY KEY,
                StudentID int NOT NULL,
                TotalAmount decimal(10,2) NOT NULL,
                PaymentMode nvarchar(50) NOT NULL,
                TransactionRef nvarchar(100) NULL,
                PaymentDate datetime DEFAULT GETDATE(),
                ReceiptNumber nvarchar(50) UNIQUE NOT NULL,
                CreatedBy int NULL,
                CreatedAt datetime DEFAULT GETDATE(),
                FOREIGN KEY (CreatedBy) REFERENCES UserMaster(UserID)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS FeePayment;"
        ),
        
        migrations.RunSQL(
            """
            -- Insert sample fee structure data
            IF NOT EXISTS (SELECT * FROM FeeStructure WHERE FeeName = 'Monthly Fee')
            BEGIN
                INSERT INTO FeeStructure (SchoolID, ClassID, FeeType, FeeName, Amount, IsMandatory, IsActive, CreatedBy)
                SELECT 
                    s.SchoolID, 
                    1 as ClassID, 
                    'Monthly' as FeeType, 
                    'Monthly Fee' as FeeName, 
                    500.00 as Amount, 
                    1 as IsMandatory, 
                    1 as IsActive, 
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeStructure (SchoolID, ClassID, FeeType, FeeName, Amount, IsMandatory, IsActive, CreatedBy)
                SELECT 
                    s.SchoolID, 
                    1 as ClassID, 
                    'Admission' as FeeType, 
                    'Admission Fee' as FeeName, 
                    2000.00 as Amount, 
                    1 as IsMandatory, 
                    1 as IsActive, 
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeStructure (SchoolID, ClassID, FeeType, FeeName, Amount, IsMandatory, IsActive, CreatedBy)
                SELECT 
                    s.SchoolID, 
                    1 as ClassID, 
                    'Registration' as FeeType, 
                    'Registration Fee' as FeeName, 
                    500.00 as Amount, 
                    1 as IsMandatory, 
                    1 as IsActive, 
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeStructure (SchoolID, ClassID, FeeType, FeeName, Amount, IsMandatory, IsActive, CreatedBy)
                SELECT 
                    s.SchoolID, 
                    1 as ClassID, 
                    'Material' as FeeType, 
                    'Art Material' as FeeName, 
                    200.00 as Amount, 
                    0 as IsMandatory, 
                    1 as IsActive, 
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeStructure (SchoolID, ClassID, FeeType, FeeName, Amount, IsMandatory, IsActive, CreatedBy)
                SELECT 
                    s.SchoolID, 
                    1 as ClassID, 
                    'Transport' as FeeType, 
                    'Transport' as FeeName, 
                    300.00 as Amount, 
                    0 as IsMandatory, 
                    1 as IsActive, 
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeStructure (SchoolID, ClassID, FeeType, FeeName, Amount, IsMandatory, IsActive, CreatedBy)
                SELECT 
                    s.SchoolID, 
                    1 as ClassID, 
                    'Books' as FeeType, 
                    'Books' as FeeName, 
                    400.00 as Amount, 
                    0 as IsMandatory, 
                    1 as IsActive, 
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeStructure (SchoolID, ClassID, FeeType, FeeName, Amount, IsMandatory, IsActive, CreatedBy)
                SELECT 
                    s.SchoolID, 
                    1 as ClassID, 
                    'Uniform' as FeeType, 
                    'Uniform' as FeeName, 
                    600.00 as Amount, 
                    0 as IsMandatory, 
                    1 as IsActive, 
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeStructure (SchoolID, ClassID, FeeType, FeeName, Amount, IsMandatory, IsActive, CreatedBy)
                SELECT 
                    s.SchoolID, 
                    1 as ClassID, 
                    'Fine' as FeeType, 
                    'Fine' as FeeName, 
                    50.00 as Amount, 
                    0 as IsMandatory, 
                    1 as IsActive, 
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
            END
            """,
            reverse_sql="DELETE FROM FeeStructure WHERE FeeName IN ('Monthly Fee', 'Admission Fee', 'Registration Fee', 'Art Material', 'Transport', 'Books', 'Uniform', 'Fine');"
        ),
    ]
