# Generated by Django 5.2.5 on 2025-09-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_recreate_fee_tables'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Drop foreign key constraints first, then drop tables
            IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK__StudentFe__FeeID__[0-9A-F]*')
            BEGIN
                DECLARE @sql NVARCHAR(MAX) = ''
                SELECT @sql = @sql + 'ALTER TABLE ' + OBJECT_NAME(parent_object_id) + ' DROP CONSTRAINT ' + name + ';'
                FROM sys.foreign_keys 
                WHERE referenced_object_id = OBJECT_ID('FeeStructure')
                EXEC sp_executesql @sql
            END
            
            -- Drop tables in correct order
            DROP TABLE IF EXISTS StudentFeeAssignment;
            DROP TABLE IF EXISTS FeePayment;
            DROP TABLE IF EXISTS FeeStructure;
            """,
            reverse_sql="""
            -- Note: This migration drops tables, so reverse is not possible
            -- The tables will need to be recreated if rollback is needed
            """
        ),
    ]
