# Generated by Django 5.2.5 on 2025-09-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_drop_unnecessary_fee_tables'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Create FeeType_Master table
            IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='FeeType_Master' AND xtype='U')
            CREATE TABLE FeeType_Master (
                FeeTypeId int IDENTITY(1,1) PRIMARY KEY,
                FeeTypeName nvarchar(100) NOT NULL,
                DefaultAmount decimal(10,2) NOT NULL,
                SchoolId int NOT NULL,
                IsActive bit DEFAULT 1,
                CreatedBy int NULL,
                CreatedAt datetime DEFAULT GETDATE(),
                FOREIGN KEY (SchoolId) REFERENCES SchoolMaster(SchoolID),
                FOREIGN KEY (CreatedBy) REFERENCES UserMaster(UserID)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS FeeType_Master;"
        ),
        
        migrations.RunSQL(
            """
            -- Insert sample fee types for all schools
            IF NOT EXISTS (SELECT * FROM FeeType_Master WHERE FeeTypeName = 'Monthly Fee')
            BEGIN
                INSERT INTO FeeType_Master (FeeTypeName, DefaultAmount, SchoolId, IsActive, CreatedBy)
                SELECT 
                    'Monthly Fee' as FeeTypeName,
                    500.00 as DefaultAmount,
                    s.SchoolID as SchoolId,
                    1 as IsActive,
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeType_Master (FeeTypeName, DefaultAmount, SchoolId, IsActive, CreatedBy)
                SELECT 
                    'Admission Fee' as FeeTypeName,
                    2000.00 as DefaultAmount,
                    s.SchoolID as SchoolId,
                    1 as IsActive,
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeType_Master (FeeTypeName, DefaultAmount, SchoolId, IsActive, CreatedBy)
                SELECT 
                    'Registration Fee' as FeeTypeName,
                    500.00 as DefaultAmount,
                    s.SchoolID as SchoolId,
                    1 as IsActive,
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeType_Master (FeeTypeName, DefaultAmount, SchoolId, IsActive, CreatedBy)
                SELECT 
                    'Transport Fee' as FeeTypeName,
                    300.00 as DefaultAmount,
                    s.SchoolID as SchoolId,
                    1 as IsActive,
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
                
                INSERT INTO FeeType_Master (FeeTypeName, DefaultAmount, SchoolId, IsActive, CreatedBy)
                SELECT 
                    'Books Fee' as FeeTypeName,
                    400.00 as DefaultAmount,
                    s.SchoolID as SchoolId,
                    1 as IsActive,
                    1 as CreatedBy
                FROM SchoolMaster s 
                WHERE s.IsDeleted = 0;
            END
            """,
            reverse_sql="DELETE FROM FeeType_Master WHERE FeeTypeName IN ('Monthly Fee', 'Admission Fee', 'Registration Fee', 'Transport Fee', 'Books Fee');"
        ),
    ]
