# Generated by Django 5.2.5 on 2025-01-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_create_feetype_master'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Drop existing procedure if exists and create new one
            IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'Proc_Fee_Report_Get')
                DROP PROCEDURE Proc_Fee_Report_Get;
            
            CREATE PROCEDURE Proc_Fee_Report_Get
            (
                @mint_SchoolId INT,
                @mint_ClassId INT = NULL,
                @mint_SectionId INT = NULL,
                @mstr_StudentCode NVARCHAR(50) = NULL,
                @mdt_FromDate DATE = NULL,
                @mdt_ToDate DATE = NULL,
                @mstr_PaymentMode NVARCHAR(50) = NULL,
                @mstr_ReportType NVARCHAR(20) = 'SUMMARY' -- SUMMARY, DETAILED, COLLECTION, OUTSTANDING
            )
            AS
            BEGIN
                SET NOCOUNT ON;
                
                -- Set default date range if not provided (current month)
                IF @mdt_FromDate IS NULL
                    SET @mdt_FromDate = DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)
                
                IF @mdt_ToDate IS NULL
                    SET @mdt_ToDate = EOMONTH(GETDATE())
                
                -- Validate report type
                IF @mstr_ReportType NOT IN ('SUMMARY', 'DETAILED', 'COLLECTION', 'OUTSTANDING')
                    SET @mstr_ReportType = 'SUMMARY'
                
                -- =============================================
                -- SUMMARY REPORT
                -- =============================================
                IF @mstr_ReportType = 'SUMMARY'
                BEGIN
                    SELECT 
                        'SUMMARY' AS ReportType,
                        COUNT(DISTINCT p.EntityID) AS TotalStudents,
                        COUNT(p.PaymentID) AS TotalTransactions,
                        SUM(p.TotalAmount) AS TotalAmount,
                        SUM(p.PaidAmount) AS TotalPaidAmount,
                        SUM(p.TotalAmount - p.PaidAmount) AS TotalOutstanding,
                        AVG(p.TotalAmount) AS AverageAmount,
                        AVG(p.PaidAmount) AS AveragePaidAmount,
                        COUNT(CASE WHEN p.PaymentMode = 'Cash' THEN 1 END) AS CashTransactions,
                        COUNT(CASE WHEN p.PaymentMode = 'Card' THEN 1 END) AS CardTransactions,
                        COUNT(CASE WHEN p.PaymentMode = 'UPI' THEN 1 END) AS UPITransactions,
                        COUNT(CASE WHEN p.PaymentMode = 'Bank Transfer' THEN 1 END) AS BankTransferTransactions,
                        @mdt_FromDate AS FromDate,
                        @mdt_ToDate AS ToDate
                    FROM Payment p
                    INNER JOIN Student s ON p.EntityID = s.StudentID
                    WHERE p.SchoolID = @mint_SchoolId
                        AND p.EntityType = 'Student'
                        AND p.PaymentFor = 'Fees'
                        AND p.IsDeleted = 0
                        AND p.PaymentDate BETWEEN @mdt_FromDate AND @mdt_ToDate
                        AND (@mint_ClassId IS NULL OR s.AdmissionClass = @mint_ClassId)
                        AND (@mint_SectionId IS NULL OR s.Section = @mint_SectionId)
                        AND (@mstr_StudentCode IS NULL OR s.StudentCode = @mstr_StudentCode)
                        AND (@mstr_PaymentMode IS NULL OR p.PaymentMode = @mstr_PaymentMode)
                END
                
                -- =============================================
                -- DETAILED REPORT
                -- =============================================
                ELSE IF @mstr_ReportType = 'DETAILED'
                BEGIN
                    SELECT 
                        'DETAILED' AS ReportType,
                        s.StudentCode,
                        s.FullName,
                        c.ClassName,
                        ISNULL(sec.SectionName, 'N/A') AS SectionName,
                        p.ReceiptNumber,
                        FORMAT(p.PaymentDate, 'dd MMM yyyy') AS PaymentDate,
                        FORMAT(CAST(CONVERT(char(6), p.PaymentMonth) + '01' AS date), 'MMM yyyy') AS PaymentMonth,
                        p.PaymentMode,
                        p.TotalAmount,
                        p.PaidAmount,
                        (p.TotalAmount - p.PaidAmount) AS OutstandingAmount,
                        CASE 
                            WHEN p.PaidAmount = p.TotalAmount THEN 'Paid'
                            WHEN p.PaidAmount > 0 THEN 'Partial'
                            ELSE 'Unpaid'
                        END AS PaymentStatus,
                        p.CreatedAt AS TransactionTime
                    FROM Payment p
                    INNER JOIN Student s ON p.EntityID = s.StudentID
                    INNER JOIN ClassMaster c ON s.AdmissionClass = c.ClassID
                    LEFT JOIN SectionMaster sec ON s.Section = sec.SectionID
                    WHERE p.SchoolID = @mint_SchoolId
                        AND p.EntityType = 'Student'
                        AND p.PaymentFor = 'Fees'
                        AND p.IsDeleted = 0
                        AND p.PaymentDate BETWEEN @mdt_FromDate AND @mdt_ToDate
                        AND (@mint_ClassId IS NULL OR s.AdmissionClass = @mint_ClassId)
                        AND (@mint_SectionId IS NULL OR s.Section = @mint_SectionId)
                        AND (@mstr_StudentCode IS NULL OR s.StudentCode = @mstr_StudentCode)
                        AND (@mstr_PaymentMode IS NULL OR p.PaymentMode = @mstr_PaymentMode)
                    ORDER BY p.PaymentDate DESC, s.StudentCode
                END
                
                -- =============================================
                -- COLLECTION REPORT (Daily/Weekly/Monthly)
                -- =============================================
                ELSE IF @mstr_ReportType = 'COLLECTION'
                BEGIN
                    SELECT 
                        'COLLECTION' AS ReportType,
                        FORMAT(p.PaymentDate, 'yyyy-MM-dd') AS CollectionDate,
                        FORMAT(p.PaymentDate, 'dd MMM yyyy') AS FormattedDate,
                        COUNT(p.PaymentID) AS TransactionCount,
                        COUNT(DISTINCT p.EntityID) AS StudentCount,
                        SUM(p.PaidAmount) AS TotalCollection,
                        SUM(CASE WHEN p.PaymentMode = 'Cash' THEN p.PaidAmount ELSE 0 END) AS CashCollection,
                        SUM(CASE WHEN p.PaymentMode = 'Card' THEN p.PaidAmount ELSE 0 END) AS CardCollection,
                        SUM(CASE WHEN p.PaymentMode = 'UPI' THEN p.PaidAmount ELSE 0 END) AS UPICollection,
                        SUM(CASE WHEN p.PaymentMode = 'Bank Transfer' THEN p.PaidAmount ELSE 0 END) AS BankTransferCollection
                    FROM Payment p
                    INNER JOIN Student s ON p.EntityID = s.StudentID
                    WHERE p.SchoolID = @mint_SchoolId
                        AND p.EntityType = 'Student'
                        AND p.PaymentFor = 'Fees'
                        AND p.IsDeleted = 0
                        AND p.PaymentDate BETWEEN @mdt_FromDate AND @mdt_ToDate
                        AND (@mint_ClassId IS NULL OR s.AdmissionClass = @mint_ClassId)
                        AND (@mint_SectionId IS NULL OR s.Section = @mint_SectionId)
                        AND (@mstr_StudentCode IS NULL OR s.StudentCode = @mstr_StudentCode)
                        AND (@mstr_PaymentMode IS NULL OR p.PaymentMode = @mstr_PaymentMode)
                    GROUP BY p.PaymentDate
                    ORDER BY p.PaymentDate DESC
                END
                
                -- =============================================
                -- OUTSTANDING REPORT
                -- =============================================
                ELSE IF @mstr_ReportType = 'OUTSTANDING'
                BEGIN
                    SELECT 
                        'OUTSTANDING' AS ReportType,
                        s.StudentCode,
                        s.FullName,
                        c.ClassName,
                        ISNULL(sec.SectionName, 'N/A') AS SectionName,
                        s.GuardianName,
                        s.ParentMobile,
                        SUM(p.TotalAmount) AS TotalFeeAmount,
                        SUM(p.PaidAmount) AS TotalPaidAmount,
                        SUM(p.TotalAmount - p.PaidAmount) AS OutstandingAmount,
                        COUNT(p.PaymentID) AS TotalTransactions,
                        COUNT(CASE WHEN p.PaidAmount = p.TotalAmount THEN 1 END) AS PaidTransactions,
                        COUNT(CASE WHEN p.PaidAmount < p.TotalAmount AND p.PaidAmount > 0 THEN 1 END) AS PartialTransactions,
                        COUNT(CASE WHEN p.PaidAmount = 0 THEN 1 END) AS UnpaidTransactions,
                        MAX(p.PaymentDate) AS LastPaymentDate,
                        MIN(p.PaymentDate) AS FirstPaymentDate
                    FROM Payment p
                    INNER JOIN Student s ON p.EntityID = s.StudentID
                    INNER JOIN ClassMaster c ON s.AdmissionClass = c.ClassID
                    LEFT JOIN SectionMaster sec ON s.Section = sec.SectionID
                    WHERE p.SchoolID = @mint_SchoolId
                        AND p.EntityType = 'Student'
                        AND p.PaymentFor = 'Fees'
                        AND p.IsDeleted = 0
                        AND (@mint_ClassId IS NULL OR s.AdmissionClass = @mint_ClassId)
                        AND (@mint_SectionId IS NULL OR s.Section = @mint_SectionId)
                        AND (@mstr_StudentCode IS NULL OR s.StudentCode = @mstr_StudentCode)
                    GROUP BY s.StudentID, s.StudentCode, s.FullName, c.ClassName, sec.SectionName, s.GuardianName, s.ParentMobile
                    HAVING SUM(p.TotalAmount - p.PaidAmount) > 0
                    ORDER BY OutstandingAmount DESC, s.StudentCode
                END
                
                -- =============================================
                -- CLASS-WISE SUMMARY (Additional data for all report types)
                -- =============================================
                SELECT 
                    'CLASS_SUMMARY' AS ReportType,
                    c.ClassName,
                    COUNT(DISTINCT s.StudentID) AS TotalStudents,
                    COUNT(p.PaymentID) AS TotalTransactions,
                    SUM(p.TotalAmount) AS TotalAmount,
                    SUM(p.PaidAmount) AS TotalPaidAmount,
                    SUM(p.TotalAmount - p.PaidAmount) AS OutstandingAmount,
                    AVG(p.TotalAmount) AS AverageAmount,
                    AVG(p.PaidAmount) AS AveragePaidAmount
                FROM Payment p
                INNER JOIN Student s ON p.EntityID = s.StudentID
                INNER JOIN ClassMaster c ON s.AdmissionClass = c.ClassID
                WHERE p.SchoolID = @mint_SchoolId
                    AND p.EntityType = 'Student'
                    AND p.PaymentFor = 'Fees'
                    AND p.IsDeleted = 0
                    AND p.PaymentDate BETWEEN @mdt_FromDate AND @mdt_ToDate
                    AND (@mint_ClassId IS NULL OR s.AdmissionClass = @mint_ClassId)
                    AND (@mint_SectionId IS NULL OR s.Section = @mint_SectionId)
                    AND (@mstr_StudentCode IS NULL OR s.StudentCode = @mstr_StudentCode)
                    AND (@mstr_PaymentMode IS NULL OR p.PaymentMode = @mstr_PaymentMode)
                GROUP BY c.ClassID, c.ClassName
                ORDER BY c.ClassName
                
                -- =============================================
                -- PAYMENT MODE SUMMARY (Additional data for all report types)
                -- =============================================
                SELECT 
                    'PAYMENT_MODE_SUMMARY' AS ReportType,
                    p.PaymentMode,
                    COUNT(p.PaymentID) AS TransactionCount,
                    SUM(p.PaidAmount) AS TotalAmount,
                    AVG(p.PaidAmount) AS AverageAmount,
                    MIN(p.PaidAmount) AS MinAmount,
                    MAX(p.PaidAmount) AS MaxAmount
                FROM Payment p
                INNER JOIN Student s ON p.EntityID = s.StudentID
                WHERE p.SchoolID = @mint_SchoolId
                    AND p.EntityType = 'Student'
                    AND p.PaymentFor = 'Fees'
                    AND p.IsDeleted = 0
                    AND p.PaymentDate BETWEEN @mdt_FromDate AND @mdt_ToDate
                    AND (@mint_ClassId IS NULL OR s.AdmissionClass = @mint_ClassId)
                    AND (@mint_SectionId IS NULL OR s.Section = @mint_SectionId)
                    AND (@mstr_StudentCode IS NULL OR s.StudentCode = @mstr_StudentCode)
                    AND (@mstr_PaymentMode IS NULL OR p.PaymentMode = @mstr_PaymentMode)
                GROUP BY p.PaymentMode
                ORDER BY TotalAmount DESC
            END
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS Proc_Fee_Report_Get"
        ),
    ]
