# Generated by Django 5.2.5 on 2025-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_create_fee_report_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTypeMaster',
            fields=[
                ('fee_type_id', models.AutoField(db_column='FeeTypeId', primary_key=True, serialize=False)),
                ('fee_type_name', models.CharField(db_column='FeeTypeName', max_length=100)),
                ('default_amount', models.DecimalField(db_column='DefaultAmount', decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'db_table': 'FeeType_Master',
                'managed': False,
            },
        ),
    ]
