# Generated by Django 5.2.5 on 2025-10-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_feetypemaster'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR ALTER PROCEDURE Proc_FeeTypeMaster_List
            (
                @mint_SchoolID INT = NULL,
                @mint_ClassID INT = NULL,
                @mvar_SearchText NVARCHAR(100) = NULL,
                @mint_PageNo INT = NULL,
                @mint_PageSize INT = NULL
            )
            AS
            BEGIN
                SET NOCOUNT ON;

                BEGIN TRY
                    DECLARE @mint_StartRow INT, @mint_EndRow INT;
                    
                    -- Calculate start and end rows for pagination
                    IF @mint_PageNo IS NOT NULL AND @mint_PageSize IS NOT NULL
                    BEGIN
                        SET @mint_StartRow = ((@mint_PageNo - 1) * @mint_PageSize) + 1;
                        SET @mint_EndRow = @mint_PageNo * @mint_PageSize;
                    END

                    ;WITH CTE_FeeType AS
                    (
                        SELECT 
                            FT.FeeTypeId,
                            FT.SchoolId,
                            S.SchoolName,
                            FT.ClassId,
                            C.ClassName,
                            FT.FeeTypeName,
                            FT.DefaultAmount,
                            FT.IsActive,
                            ROW_NUMBER() OVER (ORDER BY S.SchoolName ASC, FT.FeeTypeName ASC) AS RowNum
                        FROM FeeType_Master FT
                        LEFT JOIN SchoolMaster S ON FT.SchoolId = S.SchoolId
                        LEFT JOIN ClassMaster C ON FT.ClassId = C.ClassId
                        WHERE 
                            (@mint_SchoolID IS NULL OR FT.SchoolId = @mint_SchoolID)
                            AND (@mint_ClassID IS NULL OR FT.ClassId = @mint_ClassID)
                            AND (
                                @mvar_SearchText IS NULL 
                                OR FT.FeeTypeName LIKE '%' + @mvar_SearchText + '%'
                                OR S.SchoolName LIKE '%' + @mvar_SearchText + '%'
                                OR C.ClassName LIKE '%' + @mvar_SearchText + '%'
                            )
                    )
                    SELECT 
                        FeeTypeId,
                        SchoolId,
                        SchoolName,
                        ClassId,
                        ClassName,
                        FeeTypeName,
                        DefaultAmount,
                        IsActive,       -- 0 = Active, 1 = Inactive
                        RowNum
                    FROM CTE_FeeType
                    WHERE 
                        (@mint_PageNo IS NULL OR @mint_PageSize IS NULL)
                        OR (RowNum BETWEEN @mint_StartRow AND @mint_EndRow)
                    ORDER BY SchoolName, FeeTypeId;

                    -- 🧮 Total record count for pagination UI
                    IF @mint_PageNo IS NOT NULL AND @mint_PageSize IS NOT NULL
                    BEGIN
                        SELECT COUNT(1) AS TotalRecords
                        FROM FeeType_Master FT
                        LEFT JOIN SchoolMaster S ON FT.SchoolId = S.SchoolId
                        LEFT JOIN ClassMaster C ON FT.ClassId = C.ClassId
                        WHERE 
                            (@mint_SchoolID IS NULL OR FT.SchoolId = @mint_SchoolID)
                            AND (@mint_ClassID IS NULL OR FT.ClassId = @mint_ClassID)
                            AND (
                                @mvar_SearchText IS NULL 
                                OR FT.FeeTypeName LIKE '%' + @mvar_SearchText + '%'
                                OR S.SchoolName LIKE '%' + @mvar_SearchText + '%'
                                OR C.ClassName LIKE '%' + @mvar_SearchText + '%'
                            );
                    END
                END TRY

                BEGIN CATCH
                    SELECT 
                        ERROR_NUMBER() AS ErrorNumber,
                        ERROR_MESSAGE() AS ErrorMessage,
                        ERROR_LINE() AS ErrorLine;
                END CATCH
            END;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS Proc_FeeTypeMaster_List;"
        ),
    ]
