# Generated by Django 5.2.5 on 2025-11-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_upgrade_fee_report_procedure'),
        ('core', '0046_upgrade_fee_report_procedure'),
    ]

    operations = [
    ]
