# Generated by Django 5.0.14 on 2025-11-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20251110_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAMaster',
            fields=[
                ('sla_id', models.AutoField(db_column='SLAID', primary_key=True, serialize=False)),
                ('sla_name', models.CharField(db_column='SLAName', max_length=100)),
                ('response_time_hours', models.IntegerField(db_column='ResponseTimeHours')),
                ('resolution_time_hours', models.IntegerField(db_column='ResolutionTimeHours')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'db_table': 'SLAMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('assignment_id', models.AutoField(db_column='AssignmentID', primary_key=True, serialize=False)),
                ('assignment_notes', models.CharField(blank=True, db_column='AssignmentNotes', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('assigned_at', models.DateTimeField(db_column='AssignedAt')),
                ('unassigned_at', models.DateTimeField(blank=True, db_column='UnassignedAt', null=True)),
            ],
            options={
                'db_table': 'TicketAssignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketAttachments',
            fields=[
                ('attachment_id', models.AutoField(db_column='AttachmentID', primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_column='FileName', max_length=255)),
                ('file_size', models.BigIntegerField(db_column='FileSize')),
                ('file_type', models.CharField(blank=True, db_column='FileType', max_length=100, null=True)),
                ('file_path', models.CharField(db_column='FilePath', max_length=500)),
                ('file_data', models.BinaryField(blank=True, db_column='FileData', max_length='max', null=True)),
                ('uploaded_at', models.DateTimeField(db_column='UploadedAt')),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DeletedAt', null=True)),
            ],
            options={
                'db_table': 'TicketAttachments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='CategoryName', max_length=100)),
                ('category_code', models.CharField(db_column='CategoryCode', max_length=20)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'db_table': 'TicketCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketComments',
            fields=[
                ('comment_id', models.AutoField(db_column='CommentID', primary_key=True, serialize=False)),
                ('comment_text', models.TextField(db_column='CommentText')),
                ('is_internal', models.BooleanField(db_column='IsInternal', default=False)),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DeletedAt', null=True)),
            ],
            options={
                'db_table': 'TicketComments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMaster',
            fields=[
                ('ticket_id', models.AutoField(db_column='TicketID', primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_column='TicketNumber', max_length=50, unique=True)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('description', models.TextField(db_column='Description')),
                ('resolution_notes', models.TextField(blank=True, db_column='ResolutionNotes', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_column='ResolvedAt', null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_column='ClosedAt', null=True)),
                ('reopened_count', models.IntegerField(db_column='ReopenedCount', default=0)),
                ('last_reopened_at', models.DateTimeField(blank=True, db_column='LastReopenedAt', null=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DeletedAt', null=True)),
            ],
            options={
                'db_table': 'TicketMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketNotificationLog',
            fields=[
                ('notification_id', models.AutoField(db_column='NotificationID', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(db_column='NotificationType', max_length=50)),
                ('notification_event', models.CharField(db_column='NotificationEvent', max_length=50)),
                ('subject', models.CharField(blank=True, db_column='Subject', max_length=255, null=True)),
                ('message_body', models.TextField(blank=True, db_column='MessageBody', null=True)),
                ('is_sent', models.BooleanField(db_column='IsSent', default=False)),
                ('sent_at', models.DateTimeField(blank=True, db_column='SentAt', null=True)),
                ('error_message', models.TextField(blank=True, db_column='ErrorMessage', null=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'TicketNotificationLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('priority_id', models.AutoField(db_column='PriorityID', primary_key=True, serialize=False)),
                ('priority_name', models.CharField(db_column='PriorityName', max_length=50)),
                ('priority_code', models.CharField(db_column='PriorityCode', max_length=20)),
                ('priority_level', models.IntegerField(db_column='PriorityLevel')),
                ('color_code', models.CharField(blank=True, db_column='ColorCode', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'db_table': 'TicketPriority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('status_id', models.AutoField(db_column='StatusID', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='StatusName', max_length=50)),
                ('status_code', models.CharField(db_column='StatusCode', max_length=20)),
                ('status_order', models.IntegerField(db_column='StatusOrder')),
                ('color_code', models.CharField(blank=True, db_column='ColorCode', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'db_table': 'TicketStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('history_id', models.AutoField(db_column='HistoryID', primary_key=True, serialize=False)),
                ('change_reason', models.CharField(blank=True, db_column='ChangeReason', max_length=500, null=True)),
                ('is_reopen_action', models.BooleanField(db_column='IsReopenAction', default=False)),
                ('changed_at', models.DateTimeField(db_column='ChangedAt')),
            ],
            options={
                'db_table': 'TicketStatusHistory',
                'managed': False,
            },
        ),
    ]
