# Generated by Django 5.0.14 on 2025-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_slamaster_ticketassignment_ticketattachments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportError',
            fields=[
                ('error_id', models.AutoField(db_column='ErrorID', primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(db_column='RowNumber')),
                ('column_name', models.CharField(blank=True, db_column='ColumnName', max_length=100, null=True)),
                ('column_value', models.CharField(blank=True, db_column='ColumnValue', max_length=500, null=True)),
                ('error_type', models.CharField(choices=[('Validation', 'Validation Error'), ('FK', 'Foreign Key Error'), ('Duplicate', 'Duplicate Record'), ('Format', 'Format Error'), ('Required', 'Required Field Missing'), ('Range', 'Value Out of Range'), ('Exception', 'System Exception')], db_column='ErrorType', max_length=50)),
                ('error_message', models.CharField(db_column='ErrorMessage', max_length=1000)),
                ('error_severity', models.CharField(choices=[('Warning', 'Warning'), ('Error', 'Error'), ('Critical', 'Critical')], db_column='ErrorSeverity', default='Error', max_length=20)),
                ('row_data', models.TextField(blank=True, db_column='RowData', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'DataImportErrors',
                'ordering': ['row_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('import_id', models.AutoField(db_column='ImportID', primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('Students', 'Students'), ('Teachers', 'Teachers'), ('Salary', 'Salary'), ('Fee', 'Fee History'), ('Attendance', 'Attendance History'), ('Exam', 'Exams'), ('ExamResult', 'Exam Results'), ('ClassMaster', 'Class Master'), ('SectionMaster', 'Section Master'), ('SubjectMaster', 'Subject Master')], db_column='ImportType', max_length=50)),
                ('file_name', models.CharField(db_column='FileName', max_length=255)),
                ('file_path', models.CharField(blank=True, db_column='FilePath', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, db_column='FileSize', null=True)),
                ('total_rows', models.IntegerField(db_column='TotalRows')),
                ('valid_rows', models.IntegerField(db_column='ValidRows', default=0)),
                ('invalid_rows', models.IntegerField(db_column='InvalidRows', default=0)),
                ('success_rows', models.IntegerField(db_column='SuccessRows', default=0)),
                ('failed_rows', models.IntegerField(db_column='FailedRows', default=0)),
                ('skipped_rows', models.IntegerField(db_column='SkippedRows', default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Validating', 'Validating'), ('Validated', 'Validated'), ('Importing', 'Importing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('PartialSuccess', 'Partial Success')], db_column='Status', default='Pending', max_length=20)),
                ('validation_started_at', models.DateTimeField(blank=True, db_column='ValidationStartedAt', null=True)),
                ('validation_completed_at', models.DateTimeField(blank=True, db_column='ValidationCompletedAt', null=True)),
                ('import_started_at', models.DateTimeField(blank=True, db_column='ImportStartedAt', null=True)),
                ('import_completed_at', models.DateTimeField(blank=True, db_column='ImportCompletedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('error_file_path', models.CharField(blank=True, db_column='ErrorFilePath', max_length=500, null=True)),
                ('error_file_generated', models.BooleanField(db_column='ErrorFileGenerated', default=False)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'DataImportLog',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
