# Generated by Django 5.0.14 on 2025-11-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_update_attendance_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SLAMaster',
        ),
        migrations.DeleteModel(
            name='TicketAssignment',
        ),
        migrations.DeleteModel(
            name='TicketAttachments',
        ),
        migrations.DeleteModel(
            name='TicketCategory',
        ),
        migrations.DeleteModel(
            name='TicketComments',
        ),
        migrations.DeleteModel(
            name='TicketMaster',
        ),
        migrations.DeleteModel(
            name='TicketNotificationLog',
        ),
        migrations.DeleteModel(
            name='TicketPriority',
        ),
        migrations.DeleteModel(
            name='TicketStatus',
        ),
        migrations.DeleteModel(
            name='TicketStatusHistory',
        ),
    ]
