# Generated by Antigravity

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_delete_slamaster_delete_ticketassignment_and_more'),
    ]

    operations = [
        # Fix Proc_FeeTypeMaster_List: Cast boolean IsActive to int for comparison
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION "Proc_FeeTypeMaster_List"(
                p_SchoolID INT,
                p_ClassID INT,
                p_SearchText VARCHAR(100),
                p_PageNo INT DEFAULT 1,
                p_PageSize INT DEFAULT 10
            ) 
            RETURNS TABLE (
                "FeeTypeId" INT,
                "SchoolId" INT,
                "SchoolName" VARCHAR,
                "ClassId" INT,
                "ClassName" VARCHAR,
                "FeeTypeName" VARCHAR,
                "DefaultAmount" DECIMAL,
                "IsActive" INT -- 0=Active, 1=Inactive (Legacy)
            ) AS $$
            DECLARE
                v_Offset INT;
            BEGIN
                v_Offset := (p_PageNo - 1) * p_PageSize;

                RETURN QUERY
                SELECT 
                    ft."FeeTypeId",
                    ft."SchoolId",
                    s."SchoolName",
                    ft."ClassId",
                    c."ClassName",
                    ft."FeeTypeName",
                    CAST(ft."DefaultAmount" AS DECIMAL(18,2)),
                    CAST(ft."IsActive" AS INT)
                FROM "FeeType_Master" ft
                LEFT JOIN "SchoolMaster" s ON ft."SchoolId" = s."SchoolID"
                LEFT JOIN "ClassMaster" c ON ft."ClassId" = c."ClassID"
                WHERE 
                    (p_SchoolID IS NULL OR ft."SchoolId" = p_SchoolID)
                    AND (p_ClassID IS NULL OR ft."ClassId" = p_ClassID)
                    AND (p_SearchText IS NULL OR ft."FeeTypeName" ILIKE '%' || p_SearchText || '%')
                    AND CAST(ft."IsActive" AS INT) IN (0, 1) -- Fix for boolean type error
                ORDER BY ft."FeeTypeName"
                LIMIT p_PageSize OFFSET v_Offset;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS \"Proc_FeeTypeMaster_List\";"
        ),

        # Rewrite Proc_Ticket_Insights_Dashboard for Postgres JSON
        migrations.RunSQL(
            """
            DROP PROCEDURE IF EXISTS "Proc_Ticket_Insights_Dashboard";
            DROP FUNCTION IF EXISTS "Proc_Ticket_Insights_Dashboard";
            
            CREATE OR REPLACE FUNCTION "Proc_Ticket_Insights_Dashboard"(
                p_UserID INT,
                p_RoleName VARCHAR(50),
                p_StartDate DATE DEFAULT NULL,
                p_EndDate DATE DEFAULT NULL
            )
            RETURNS TABLE (
                stats JSON,
                trends JSON,
                categories JSON,
                priorities JSON,
                performers JSON,
                schools JSON
            )
            AS $$
            DECLARE
                v_UserSchoolID INT;
                v_StartDate DATE := p_StartDate;
                v_EndDate DATE := p_EndDate;
            BEGIN
                IF v_StartDate IS NULL THEN v_StartDate := CURRENT_DATE - INTERVAL '30 days'; END IF;
                IF v_EndDate IS NULL THEN v_EndDate := CURRENT_DATE; END IF;
                
                SELECT "SchoolID" INTO v_UserSchoolID FROM "UserMaster" WHERE "UserID" = p_UserID;
                
                RETURN QUERY
                SELECT
                    -- 1. Overall Statistics
                    (SELECT json_build_object(
                        'TotalTickets', COUNT(*),
                        'OpenTickets', SUM(CASE WHEN "CurrentStatus" = 'Open' THEN 1 ELSE 0 END),
                        'InProgressTickets', SUM(CASE WHEN "CurrentStatus" = 'In Progress' THEN 1 ELSE 0 END),
                        'ResolvedTickets', SUM(CASE WHEN "CurrentStatus" = 'Resolved' THEN 1 ELSE 0 END),
                        'ClosedTickets', SUM(CASE WHEN "CurrentStatus" = 'Closed' THEN 1 ELSE 0 END),
                        'ReopenedTickets', SUM(CASE WHEN "CurrentStatus" = 'Reopened' THEN 1 ELSE 0 END),
                        'AvgResolutionTimeHours', AVG(EXTRACT(EPOCH FROM ("ResolvedAt" - "CreatedAt"))/3600),
                        'CriticalTickets', SUM(CASE WHEN "Priority" = 4 THEN 1 ELSE 0 END),
                        'HighTickets', SUM(CASE WHEN "Priority" = 3 THEN 1 ELSE 0 END),
                        'EmailTickets', 0, 
                        'CallTickets', 0,
                        'WebsiteTickets', 0
                    ) FROM "TicketMaster"
                    WHERE "IsDeleted" = FALSE
                        AND CAST("CreatedAt" AS DATE) BETWEEN v_StartDate AND v_EndDate
                        AND (p_RoleName = 'Super Admin' OR "SchoolID" = v_UserSchoolID)
                        AND (p_RoleName != 'Support Executive' OR "AssignedToUserID" = p_UserID)
                    ) as stats,

                    -- 2. Trends (Daily)
                    (SELECT COALESCE(json_agg(row_to_json(t)), '[]'::json) FROM (
                        SELECT 
                            d.day::date as "Date",
                            COALESCE(COUNT(tm."TicketID"), 0) as "TicketCount",
                            COALESCE(SUM(CASE WHEN tm."CurrentStatus" IN ('Resolved', 'Closed') THEN 1 ELSE 0 END), 0) as "ResolvedCount"
                        FROM generate_series(v_StartDate, v_EndDate, interval '1 day') as d(day)
                        LEFT JOIN "TicketMaster" tm ON CAST(tm."CreatedAt" AS DATE) = d.day::date
                            AND tm."IsDeleted" = FALSE
                            AND (p_RoleName = 'Super Admin' OR tm."SchoolID" = v_UserSchoolID)
                            AND (p_RoleName != 'Support Executive' OR tm."AssignedToUserID" = p_UserID)
                        GROUP BY d.day
                        ORDER BY d.day DESC
                    ) t) as trends,

                    -- 3. Categories
                    (SELECT COALESCE(json_agg(row_to_json(c)), '[]'::json) FROM (
                        SELECT 
                            tc."CategoryName",
                            COUNT(tm."TicketID") as "TicketCount",
                            SUM(CASE WHEN tm."CurrentStatus" IN ('Resolved', 'Closed') THEN 1 ELSE 0 END) as "ResolvedCount",
                            ROUND((CASE WHEN COUNT(tm."TicketID") > 0 THEN SUM(CASE WHEN tm."CurrentStatus" IN ('Resolved', 'Closed') THEN 1 ELSE 0 END) * 100.0 / COUNT(tm."TicketID") ELSE 0 END)::numeric, 2) as "ResolutionRate"
                        FROM "TicketMaster" tm
                        JOIN "TicketCategory" tc ON tm."CategoryID" = tc."CategoryID"
                        WHERE tm."IsDeleted" = FALSE
                            AND CAST(tm."CreatedAt" AS DATE) BETWEEN v_StartDate AND v_EndDate
                            AND (p_RoleName = 'Super Admin' OR tm."SchoolID" = v_UserSchoolID)
                            AND (p_RoleName != 'Support Executive' OR tm."AssignedToUserID" = p_UserID)
                        GROUP BY tc."CategoryName"
                        ORDER BY "TicketCount" DESC
                    ) c) as categories,
                    
                    -- 4. Priorities
                    (SELECT COALESCE(json_agg(row_to_json(p)), '[]'::json) FROM (
                         SELECT 
                            CASE "Priority" WHEN 1 THEN 'Low' WHEN 2 THEN 'Medium' WHEN 3 THEN 'High' WHEN 4 THEN 'Critical' END as "PriorityName",
                            "Priority",
                            COUNT(*) as "TicketCount",
                             ROUND((COUNT(*) * 100.0 / NULLIF(SUM(COUNT(*)) OVER(), 0))::numeric, 2) as "Percentage"
                        FROM "TicketMaster"
                        WHERE "IsDeleted" = FALSE
                            AND CAST("CreatedAt" AS DATE) BETWEEN v_StartDate AND v_EndDate
                            AND (p_RoleName = 'Super Admin' OR "SchoolID" = v_UserSchoolID)
                            AND (p_RoleName != 'Support Executive' OR "AssignedToUserID" = p_UserID)
                        GROUP BY "Priority"
                        ORDER BY "Priority" DESC
                    ) p) as priorities,

                    -- 5. Top Performers
                    (SELECT COALESCE(json_agg(row_to_json(pf)), '[]'::json) FROM (
                        SELECT 
                            u."UserName",
                            COUNT(*) as "AssignedTickets",
                            SUM(CASE WHEN tm."CurrentStatus" IN ('Resolved', 'Closed') THEN 1 ELSE 0 END) as "ResolvedTickets",
                            ROUND((CASE WHEN COUNT(*) > 0 THEN SUM(CASE WHEN tm."CurrentStatus" IN ('Resolved', 'Closed') THEN 1 ELSE 0 END) * 100.0 / COUNT(*) ELSE 0 END)::numeric, 2) as "ResolutionRate",
                            ROUND(AVG(CASE WHEN tm."ResolvedAt" IS NOT NULL THEN EXTRACT(EPOCH FROM (tm."ResolvedAt" - tm."CreatedAt"))/3600 ELSE NULL END)::numeric, 1) as "AvgResolutionTimeHours"
                        FROM "TicketMaster" tm
                        JOIN "UserMaster" u ON tm."AssignedToUserID" = u."UserID"
                        WHERE tm."IsDeleted" = FALSE
                            AND tm."AssignedToUserID" IS NOT NULL
                            AND CAST(tm."CreatedAt" AS DATE) BETWEEN v_StartDate AND v_EndDate
                            AND (p_RoleName IN ('Super Admin', 'School Admin'))
                            AND (p_RoleName = 'Super Admin' OR tm."SchoolID" = v_UserSchoolID)
                        GROUP BY u."UserName"
                        ORDER BY "ResolvedTickets" DESC
                        LIMIT 5
                    ) pf) as performers,

                    -- 6. Schools
                    (SELECT COALESCE(json_agg(row_to_json(sc)), '[]'::json) FROM (
                         SELECT 
                            s."SchoolName",
                            COUNT(*) as "TicketCount",
                            SUM(CASE WHEN tm."CurrentStatus" = 'Open' THEN 1 ELSE 0 END) as "OpenTickets",
                            SUM(CASE WHEN tm."CurrentStatus" IN ('Resolved', 'Closed') THEN 1 ELSE 0 END) as "ResolvedTickets"
                        FROM "TicketMaster" tm
                        JOIN "SchoolMaster" s ON tm."SchoolID" = s."SchoolID"
                        WHERE tm."IsDeleted" = FALSE
                            AND CAST(tm."CreatedAt" AS DATE) BETWEEN v_StartDate AND v_EndDate
                            AND (p_RoleName = 'Super Admin')
                        GROUP BY s."SchoolName"
                        ORDER BY "TicketCount" DESC
                        LIMIT 10
                    ) sc) as schools;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS \"Proc_Ticket_Insights_Dashboard\";"
        ),
    ]
