# Generated by Antigravity

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_fix_db_issues'),
    ]

    operations = [
        # Fix Proc_FeeTypeMaster_Manage: Use CreatedAt/UpdatedAt instead of CreatedDate/UpdatedDate
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION "Proc_FeeTypeMaster_Manage"(
                p_Action VARCHAR(20),
                p_FeeTypeId INT,
                p_SchoolId INT,
                p_ClassId INT,
                p_FeeTypeName VARCHAR(100),
                p_DefaultAmount DECIMAL(18,2),
                p_IsActive BOOLEAN,    -- Python passes boolean, but DB uses INT (0=Active, 1=Inactive)
                p_UserId INT
            )
            RETURNS VARCHAR AS $$
            DECLARE
                v_IsActiveInt INT;
                v_Message VARCHAR(500);
                v_Status VARCHAR(20);
            BEGIN
                -- Convert Boolean IsActive to Int (0=Active, 1=Inactive)
                IF p_IsActive THEN
                    v_IsActiveInt := 0; -- Active
                ELSE
                    v_IsActiveInt := 1; -- Inactive
                END IF;

                IF p_Action = 'INSERT' THEN
                    INSERT INTO "FeeType_Master" (
                        "SchoolId", "ClassId", "FeeTypeName", "DefaultAmount", "IsActive", "CreatedBy", "CreatedAt"
                    ) VALUES (
                        p_SchoolId, p_ClassId, p_FeeTypeName, p_DefaultAmount, v_IsActiveInt, p_UserId, NOW()
                    );
                    
                    v_Status := 'success';
                    v_Message := 'Fee Type added successfully.';

                ELSIF p_Action = 'UPDATE' THEN
                    UPDATE "FeeType_Master"
                    SET 
                        "SchoolId" = p_SchoolId,
                        "ClassId" = p_ClassId,
                        "FeeTypeName" = p_FeeTypeName,
                        "DefaultAmount" = p_DefaultAmount,
                        "IsActive" = v_IsActiveInt,
                        "UpdatedBy" = p_UserId,
                        "UpdatedAt" = NOW()
                    WHERE "FeeTypeId" = p_FeeTypeId;
                    
                    v_Status := 'success';
                    v_Message := 'Fee Type updated successfully.';

                ELSIF p_Action = 'DELETE' THEN
                    -- Soft Delete: Set IsActive to 1 (Inactive)
                    UPDATE "FeeType_Master"
                    SET 
                        "IsActive" = 1,
                        "UpdatedBy" = p_UserId,
                        "UpdatedAt" = NOW()
                    WHERE "FeeTypeId" = p_FeeTypeId;
                    
                    v_Status := 'success';
                    v_Message := 'Fee Type deleted successfully.';
                    
                ELSIF p_Action = 'RESTORE' THEN
                    -- Restore: Set IsActive to 0 (Active)
                    UPDATE "FeeType_Master"
                    SET 
                        "IsActive" = 0,
                        "UpdatedBy" = p_UserId,
                        "UpdatedAt" = NOW()
                    WHERE "FeeTypeId" = p_FeeTypeId;
                    
                    v_Status := 'success';
                    v_Message := 'Fee Type restored successfully.';
                END IF;

                RETURN '{"status": "' || v_Status || '", "message": "' || v_Message || '"}';
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS \"Proc_FeeTypeMaster_Manage\";"
        ),
    ]
