# Generated by Antigravity

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_fix_feetype_procedures'),
    ]

    operations = [
        # Fix Proc_FeeTypeMaster_Manage: Use Boolean values for IsActive instead of Int
        # Also maintain the legacy logic where False (0) = Active, True (1) = Inactive
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION "Proc_FeeTypeMaster_Manage"(
                p_Action VARCHAR(20),
                p_FeeTypeId INT,
                p_SchoolId INT,
                p_ClassId INT,
                p_FeeTypeName VARCHAR(100),
                p_DefaultAmount DECIMAL(18,2),
                p_IsActive BOOLEAN,    
                p_UserId INT
            )
            RETURNS VARCHAR AS $$
            DECLARE
                v_IsActiveDB BOOLEAN;
                v_Message VARCHAR(500);
                v_Status VARCHAR(20);
            BEGIN
                -- Logic Inversion: DB uses False for Active (0) and True for Inactive (1)
                -- Input p_IsActive is True for Active.
                IF p_IsActive THEN
                    v_IsActiveDB := FALSE; -- Active
                ELSE
                    v_IsActiveDB := TRUE; -- Inactive
                END IF;

                IF p_Action = 'INSERT' THEN
                    INSERT INTO "FeeType_Master" (
                        "SchoolId", "ClassId", "FeeTypeName", "DefaultAmount", "IsActive", "CreatedBy", "CreatedAt"
                    ) VALUES (
                        p_SchoolId, p_ClassId, p_FeeTypeName, p_DefaultAmount, v_IsActiveDB, p_UserId, NOW()
                    );
                    
                    v_Status := 'success';
                    v_Message := 'Fee Type added successfully.';

                ELSIF p_Action = 'UPDATE' THEN
                    UPDATE "FeeType_Master"
                    SET 
                        "SchoolId" = p_SchoolId,
                        "ClassId" = p_ClassId,
                        "FeeTypeName" = p_FeeTypeName,
                        "DefaultAmount" = p_DefaultAmount,
                        "IsActive" = v_IsActiveDB,
                        "UpdatedBy" = p_UserId,
                        "UpdatedAt" = NOW()
                    WHERE "FeeTypeId" = p_FeeTypeId;
                    
                    v_Status := 'success';
                    v_Message := 'Fee Type updated successfully.';

                ELSIF p_Action = 'DELETE' THEN
                    -- Soft Delete: Set IsActive to TRUE (Inactive)
                    UPDATE "FeeType_Master"
                    SET 
                        "IsActive" = TRUE,
                        "UpdatedBy" = p_UserId,
                        "UpdatedAt" = NOW()
                    WHERE "FeeTypeId" = p_FeeTypeId;
                    
                    v_Status := 'success';
                    v_Message := 'Fee Type deleted successfully.';
                    
                ELSIF p_Action = 'RESTORE' THEN
                    -- Restore: Set IsActive to FALSE (Active)
                    UPDATE "FeeType_Master"
                    SET 
                        "IsActive" = FALSE,
                        "UpdatedBy" = p_UserId,
                        "UpdatedAt" = NOW()
                    WHERE "FeeTypeId" = p_FeeTypeId;
                    
                    v_Status := 'success';
                    v_Message := 'Fee Type restored successfully.';
                END IF;

                RETURN '{"status": "' || v_Status || '", "message": "' || v_Message || '"}';
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS \"Proc_FeeTypeMaster_Manage\";"
        ),
    ]
