# Generated by Antigravity

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_fix_feetype_boolean_logic'),
    ]

    operations = [
        migrations.RunSQL(
            # Force Fix Class menu URLs to match Django URL patterns
            sql="""
                -- Fix Add Class URL
                UPDATE "MenuMaster" 
                SET "MenuURL" = '/class/add/'
                WHERE "MenuName" = 'Add Class' AND "IsDeleted" IS NOT TRUE;
                
                -- Fix View Class URL
                UPDATE "MenuMaster" 
                SET "MenuURL" = '/class/view/'
                WHERE "MenuName" = 'View Class' AND "IsDeleted" IS NOT TRUE;
                
                -- Fix Assign Classes URL (ensure it is consistent)
                UPDATE "MenuMaster" 
                SET "MenuURL" = '/staff/assign-classes/'
                WHERE "MenuName" = 'Assign Classes' AND "IsDeleted" IS NOT TRUE;
                
                -- Fix View Assign Class URL (ensure it is consistent)
                UPDATE "MenuMaster" 
                SET "MenuURL" = '/staff/view-assign-class/'
                WHERE "MenuName" = 'View Assign Class' AND "IsDeleted" IS NOT TRUE;
            """,
            reverse_sql="""
                -- Revert URLs (optional, but good practice to have something)
                UPDATE "MenuMaster" 
                SET "MenuURL" = '/core/class/add/'
                WHERE "MenuName" = 'Add Class' AND "IsDeleted" IS NOT TRUE;
                
                UPDATE "MenuMaster" 
                SET "MenuURL" = '/core/class/view/'
                WHERE "MenuName" = 'View Class' AND "IsDeleted" IS NOT TRUE;
            """
        ),
    ]
