# Generated by Antigravity

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_refactor_class_procedures'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Drop previous function names
            DROP FUNCTION IF EXISTS func_class_set;
            DROP FUNCTION IF EXISTS func_section_set;
            DROP FUNCTION IF EXISTS func_class_list;
            DROP FUNCTION IF EXISTS func_section_list;

            -- =============================================
            -- Function: Proc_Class_Set
            -- Description: Create or Update a Class
            -- =============================================
            CREATE OR REPLACE FUNCTION "Proc_Class_Set"(
                p_class_id INT,
                p_school_id INT,
                p_class_name VARCHAR,
                p_class_code VARCHAR,
                p_education_level VARCHAR,
                p_description VARCHAR,
                p_is_active BOOLEAN,
                p_user_id INT
            )
            RETURNS TABLE (
                "ClassID" INT, 
                "SchoolID" INT, 
                "ClassName" VARCHAR, 
                "ClassCode" VARCHAR,
                "EducationLevel" VARCHAR, 
                "Description" VARCHAR, 
                "IsActive" BOOLEAN
            ) AS $$
            DECLARE
                v_class_id INT;
            BEGIN
                -- 1. Duplicate Check
                IF EXISTS (
                    SELECT 1 FROM "ClassMaster"
                    WHERE "SchoolID" = p_school_id
                    AND ("ClassName" = p_class_name OR "ClassCode" = p_class_code)
                    AND "IsDeleted" IS FALSE
                    AND (p_class_id IS NULL OR "ClassID" != p_class_id)
                ) THEN
                    RAISE EXCEPTION 'Class with same name or code already exists in this school.';
                END IF;

                -- 2. Insert or Update
                IF p_class_id IS NULL THEN
                    INSERT INTO "ClassMaster" (
                        "SchoolID", "ClassName", "ClassCode", "EducationLevel", "Description",
                        "IsActive", "CreatedBy", "CreatedAt", "IsDeleted"
                    ) VALUES (
                        p_school_id, p_class_name, p_class_code, p_education_level, p_description,
                        p_is_active, p_user_id, CURRENT_TIMESTAMP, FALSE
                    ) RETURNING "ClassMaster"."ClassID" INTO v_class_id;
                ELSE
                    UPDATE "ClassMaster"
                    SET "ClassName" = p_class_name,
                        "ClassCode" = p_class_code,
                        "EducationLevel" = p_education_level,
                        "Description" = p_description,
                        "IsActive" = p_is_active,
                        "UpdatedBy" = p_user_id,
                        "UpdatedAt" = CURRENT_TIMESTAMP
                    WHERE "ClassID" = p_class_id AND "IsDeleted" IS FALSE
                    RETURNING "ClassMaster"."ClassID" INTO v_class_id;
                END IF;

                -- 3. Return Result
                RETURN QUERY SELECT 
                    cm."ClassID", cm."SchoolID", cm."ClassName", cm."ClassCode",
                    cm."EducationLevel", cm."Description", cm."IsActive"
                FROM "ClassMaster" cm WHERE cm."ClassID" = v_class_id;
            END;
            $$ LANGUAGE plpgsql;

            -- =============================================
            -- Function: Proc_Section_Set
            -- Description: Create or Update a Section
            -- =============================================
            CREATE OR REPLACE FUNCTION "Proc_Section_Set"(
                p_section_id INT,
                p_class_id INT,
                p_section_name VARCHAR,
                p_capacity INT,
                p_room_number VARCHAR,
                p_is_active BOOLEAN,
                p_user_id INT
            )
            RETURNS TABLE (
                "SectionID" INT, 
                "ClassID" INT, 
                "SectionName" VARCHAR
            ) AS $$
            DECLARE
                v_section_id INT;
            BEGIN
                -- 1. Duplicate Check
                IF EXISTS (
                    SELECT 1 FROM "SectionMaster"
                    WHERE "ClassID" = p_class_id
                    AND "SectionName" = p_section_name
                    AND "IsDeleted" IS FALSE
                    AND (p_section_id IS NULL OR "SectionID" != p_section_id)
                ) THEN
                    RAISE EXCEPTION 'Section with same name already exists in this class.';
                END IF;

                -- 2. Insert or Update
                IF p_section_id IS NULL THEN
                    INSERT INTO "SectionMaster" (
                        "ClassID", "SectionName", "Capacity", "RoomNumber",
                        "IsActive", "CreatedBy", "CreatedAt", "IsDeleted"
                    ) VALUES (
                        p_class_id, p_section_name, p_capacity, p_room_number,
                        p_is_active, p_user_id, CURRENT_TIMESTAMP, FALSE
                    ) RETURNING "SectionMaster"."SectionID" INTO v_section_id;
                ELSE
                    UPDATE "SectionMaster"
                    SET "SectionName" = p_section_name,
                        "Capacity" = p_capacity,
                        "RoomNumber" = p_room_number,
                        "IsActive" = p_is_active,
                        "UpdatedBy" = p_user_id,
                        "UpdatedAt" = CURRENT_TIMESTAMP
                    WHERE "SectionID" = p_section_id AND "IsDeleted" IS FALSE
                    RETURNING "SectionMaster"."SectionID" INTO v_section_id;
                END IF;

                -- 3. Return Result
                RETURN QUERY SELECT sm."SectionID", sm."ClassID", sm."SectionName"
                FROM "SectionMaster" sm WHERE sm."SectionID" = v_section_id;
            END;
            $$ LANGUAGE plpgsql;

            -- =============================================
            -- Function: Proc_Class_List
            -- Description: List Classes for a School
            -- =============================================
            CREATE OR REPLACE FUNCTION "Proc_Class_List"(p_school_id INT)
            RETURNS TABLE (
                "ClassID" INT, 
                "ClassName" VARCHAR, 
                "ClassCode" VARCHAR, 
                "EducationLevel" VARCHAR,
                "Description" VARCHAR, 
                "IsActive" BOOLEAN, 
                "TotalSections" BIGINT
            ) AS $$
            BEGIN
                RETURN QUERY
                SELECT 
                    c."ClassID", c."ClassName", c."ClassCode", c."EducationLevel",
                    c."Description", c."IsActive",
                    (SELECT COUNT(*) FROM "SectionMaster" s 
                     WHERE s."ClassID" = c."ClassID" AND s."IsDeleted" IS FALSE) as "TotalSections"
                FROM "ClassMaster" c
                WHERE c."SchoolID" = p_school_id AND c."IsDeleted" IS FALSE
                ORDER BY c."ClassName";
            END;
            $$ LANGUAGE plpgsql;

            -- =============================================
            -- Function: Proc_Section_List
            -- Description: List Sections for a Class
            -- =============================================
            CREATE OR REPLACE FUNCTION "Proc_Section_List"(p_school_id INT, p_class_id INT)
            RETURNS TABLE (
                "SectionID" INT, 
                "ClassID" INT, 
                "SectionName" VARCHAR, 
                "Capacity" INT, 
                "RoomNumber" VARCHAR, 
                "IsActive" BOOLEAN
            ) AS $$
            BEGIN
                RETURN QUERY
                SELECT 
                    s."SectionID", s."ClassID", s."SectionName", 
                    s."Capacity", s."RoomNumber", s."IsActive"
                FROM "SectionMaster" s
                JOIN "ClassMaster" c ON s."ClassID" = c."ClassID"
                WHERE c."SchoolID" = p_school_id 
                AND s."ClassID" = p_class_id 
                AND s."IsDeleted" IS FALSE
                ORDER BY s."SectionName";
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            DROP FUNCTION IF EXISTS "Proc_Class_Set";
            DROP FUNCTION IF EXISTS "Proc_Section_Set";
            DROP FUNCTION IF EXISTS "Proc_Class_List";
            DROP FUNCTION IF EXISTS "Proc_Section_List";
            """
        )
    ]
