# Generated by Antigravity - Fix ambiguous column reference

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_rename_functions'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Fix ambiguous column reference in Proc_Class_Set
            CREATE OR REPLACE FUNCTION "Proc_Class_Set"(
                p_class_id INT,
                p_school_id INT,
                p_class_name VARCHAR,
                p_class_code VARCHAR,
                p_education_level VARCHAR,
                p_description VARCHAR,
                p_is_active BOOLEAN,
                p_user_id INT
            )
            RETURNS TABLE (
                "ClassID" INT, 
                "SchoolID" INT, 
                "ClassName" VARCHAR, 
                "ClassCode" VARCHAR,
                "EducationLevel" VARCHAR, 
                "Description" VARCHAR, 
                "IsActive" BOOLEAN
            ) AS $$
            DECLARE
                v_class_id INT;
            BEGIN
                -- 1. Duplicate Check (Fixed: qualified column names with table name)
                IF EXISTS (
                    SELECT 1 FROM "ClassMaster" cm
                    WHERE cm."SchoolID" = p_school_id
                    AND (cm."ClassName" = p_class_name OR cm."ClassCode" = p_class_code)
                    AND cm."IsDeleted" IS FALSE
                    AND (p_class_id IS NULL OR cm."ClassID" != p_class_id)
                ) THEN
                    RAISE EXCEPTION 'Class with same name or code already exists in this school.';
                END IF;

                -- 2. Insert or Update
                IF p_class_id IS NULL THEN
                    INSERT INTO "ClassMaster" (
                        "SchoolID", "ClassName", "ClassCode", "EducationLevel", "Description",
                        "IsActive", "CreatedBy", "CreatedAt", "IsDeleted"
                    ) VALUES (
                        p_school_id, p_class_name, p_class_code, p_education_level, p_description,
                        p_is_active, p_user_id, CURRENT_TIMESTAMP, FALSE
                    ) RETURNING "ClassMaster"."ClassID" INTO v_class_id;
                ELSE
                    UPDATE "ClassMaster"
                    SET "ClassName" = p_class_name,
                        "ClassCode" = p_class_code,
                        "EducationLevel" = p_education_level,
                        "Description" = p_description,
                        "IsActive" = p_is_active,
                        "UpdatedBy" = p_user_id,
                        "UpdatedAt" = CURRENT_TIMESTAMP
                    WHERE "ClassID" = p_class_id AND "IsDeleted" IS FALSE
                    RETURNING  "ClassMaster"."ClassID" INTO v_class_id;
                END IF;

                -- 3. Return Result
                RETURN QUERY SELECT 
                    cm."ClassID", cm."SchoolID", cm."ClassName", cm."ClassCode",
                    cm."EducationLevel", cm."Description", cm."IsActive"
                FROM "ClassMaster" cm WHERE cm."ClassID" = v_class_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            -- Revert to original (with ambiguous column)
            CREATE OR REPLACE FUNCTION "Proc_Class_Set"(
                p_class_id INT,
                p_school_id INT,
                p_class_name VARCHAR,
                p_class_code VARCHAR,
                p_education_level VARCHAR,
                p_description VARCHAR,
                p_is_active BOOLEAN,
                p_user_id INT
            )
            RETURNS TABLE (
                "ClassID" INT, 
                "SchoolID" INT, 
                "ClassName" VARCHAR, 
                "ClassCode" VARCHAR,
                "EducationLevel" VARCHAR, 
                "Description" VARCHAR, 
                "IsActive" BOOLEAN
            ) AS $$
            DECLARE
                v_class_id INT;
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM "ClassMaster"
                    WHERE "SchoolID" = p_school_id
                    AND ("ClassName" = p_class_name OR "ClassCode" = p_class_code)
                    AND "IsDeleted" IS FALSE
                    AND (p_class_id IS NULL OR "ClassID" != p_class_id)
                ) THEN
                    RAISE EXCEPTION 'Class with same name or code already exists in this school.';
                END IF;

                IF p_class_id IS NULL THEN
                    INSERT INTO "ClassMaster" (
                        "SchoolID", "ClassName", "ClassCode", "EducationLevel", "Description",
                        "IsActive", "CreatedBy", "CreatedAt", "IsDeleted"
                    ) VALUES (
                        p_school_id, p_class_name, p_class_code, p_education_level, p_description,
                        p_is_active, p_user_id, CURRENT_TIMESTAMP, FALSE
                    ) RETURNING "ClassMaster"."ClassID" INTO v_class_id;
                ELSE
                    UPDATE "ClassMaster"
                    SET "ClassName" = p_class_name,
                        "ClassCode" = p_class_code,
                        "EducationLevel" = p_education_level,
                        "Description" = p_description,
                        "IsActive" = p_is_active,
                        "UpdatedBy" = p_user_id,
                        "UpdatedAt" = CURRENT_TIMESTAMP
                    WHERE "ClassID" = p_class_id AND "IsDeleted" IS FALSE
                    RETURNING "ClassMaster"."ClassID" INTO v_class_id;
                END IF;

                RETURN QUERY SELECT 
                    cm."ClassID", cm."SchoolID", cm."ClassName", cm."ClassCode",
                    cm."EducationLevel", cm."Description", cm."IsActive"
                FROM "ClassMaster" cm WHERE cm."ClassID" = v_class_id;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
    ]
