# Generated by Antigravity - Fix ambiguous column reference in Proc_Section_Set

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_fix_proc_class_set_ambiguous_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Fix ambiguous column reference in Proc_Section_Set
            CREATE OR REPLACE FUNCTION "Proc_Section_Set"(
                p_section_id INT,
                p_class_id INT,
                p_section_name VARCHAR,
                p_capacity INT,
                p_room_number VARCHAR,
                p_is_active BOOLEAN,
                p_user_id INT
            )
            RETURNS TABLE (
                "SectionID" INT, 
                "ClassID" INT, 
                "SectionName" VARCHAR
            ) AS $$
            DECLARE
                v_section_id INT;
            BEGIN
                -- 1. Duplicate Check (Fixed: qualified column names with table alias)
                IF EXISTS (
                    SELECT 1 FROM "SectionMaster" sm
                    WHERE sm."ClassID" = p_class_id
                    AND sm."SectionName" = p_section_name
                    AND sm."IsDeleted" IS FALSE
                    AND (p_section_id IS NULL OR sm."SectionID" != p_section_id)
                ) THEN
                    RAISE EXCEPTION 'Section with same name already exists in this class.';
                END IF;

                -- 2. Insert or Update
                IF p_section_id IS NULL THEN
                    INSERT INTO "SectionMaster" (
                        "ClassID", "SectionName", "Capacity", "RoomNumber",
                        "IsActive", "CreatedBy", "CreatedAt", "IsDeleted"
                    ) VALUES (
                        p_class_id, p_section_name, p_capacity, p_room_number,
                        p_is_active, p_user_id, CURRENT_TIMESTAMP, FALSE
                    ) RETURNING "SectionMaster"."SectionID" INTO v_section_id;
                ELSE
                    UPDATE "SectionMaster"
                    SET "SectionName" = p_section_name,
                        "Capacity" = p_capacity,
                        "RoomNumber" = p_room_number,
                        "IsActive" = p_is_active,
                        "UpdatedBy" = p_user_id,
                        "UpdatedAt" = CURRENT_TIMESTAMP
                    WHERE "SectionID" = p_section_id AND "IsDeleted" IS FALSE
                    RETURNING "SectionMaster"."SectionID" INTO v_section_id;
                END IF;

                -- 3. Return Result
                RETURN QUERY SELECT sm."SectionID", sm."ClassID", sm."SectionName"
                FROM "SectionMaster" sm WHERE sm."SectionID" = v_section_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            -- Revert to original
            CREATE OR REPLACE FUNCTION "Proc_Section_Set"(
                p_section_id INT,
                p_class_id INT,
                p_section_name VARCHAR,
                p_capacity INT,
                p_room_number VARCHAR,
                p_is_active BOOLEAN,
                p_user_id INT
            )
            RETURNS TABLE (
                "SectionID" INT, 
                "ClassID" INT, 
                "SectionName" VARCHAR
            ) AS $$
            DECLARE
                v_section_id INT;
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM "SectionMaster"
                    WHERE "ClassID" = p_class_id
                    AND "SectionName" = p_section_name
                    AND "IsDeleted" IS FALSE
                    AND (p_section_id IS NULL OR "SectionID" != p_section_id)
                ) THEN
                    RAISE EXCEPTION 'Section with same name already exists in this class.';
                END IF;

                IF p_section_id IS NULL THEN
                    INSERT INTO "SectionMaster" (
                        "ClassID", "SectionName", "Capacity", "RoomNumber",
                        "IsActive", "CreatedBy", "CreatedAt", "IsDeleted"
                    ) VALUES (
                        p_class_id, p_section_name, p_capacity, p_room_number,
                        p_is_active, p_user_id, CURRENT_TIMESTAMP, FALSE
                    ) RETURNING "SectionMaster"."SectionID" INTO v_section_id;
                ELSE
                    UPDATE "SectionMaster"
                    SET "SectionName" = p_section_name,
                        "Capacity" = p_capacity,
                        "RoomNumber" = p_room_number,
                        "IsActive" = p_is_active,
                        "UpdatedBy" = p_user_id,
                        "UpdatedAt" = CURRENT_TIMESTAMP
                    WHERE "SectionID" = p_section_id AND "IsDeleted" IS FALSE
                    RETURNING "SectionMaster"."SectionID" INTO v_section_id;
                END IF;

                RETURN QUERY SELECT sm."SectionID", sm."ClassID", sm."SectionName"
                FROM "SectionMaster" sm WHERE sm."SectionID" = v_section_id;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
    ]
