# Generated by Antigravity - Fix ambiguous SELECT in Proc_Section_Set

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_improve_proc_section_set_upsert'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Fix ambiguous SELECT in Proc_Section_Set
            CREATE OR REPLACE FUNCTION "Proc_Section_Set"(
                p_section_id INT,
                p_class_id INT,
                p_section_name VARCHAR,
                p_capacity INT,
                p_room_number VARCHAR,
                p_is_active BOOLEAN,
                p_user_id INT
            )
            RETURNS TABLE (
                "SectionID" INT, 
                "ClassID" INT, 
                "SectionName" VARCHAR
            ) AS $$
            DECLARE
                v_section_id INT;
                v_existing_id INT;
                v_is_deleted BOOLEAN;
            BEGIN
                -- 1. Check for existing record via Name (Active or Deleted)
                -- Uses table alias 'sm' to avoid ambiguity with output param "SectionID"
                SELECT sm."SectionID", sm."IsDeleted" INTO v_existing_id, v_is_deleted
                FROM "SectionMaster" sm
                WHERE sm."ClassID" = p_class_id AND sm."SectionName" = p_section_name
                LIMIT 1;

                -- Logic Flow:
                IF v_existing_id IS NOT NULL THEN
                    -- Case A: Name exists
                    IF p_section_id IS NOT NULL AND p_section_id != v_existing_id THEN
                        RAISE EXCEPTION 'Section name "%" is already used by another section.', p_section_name;
                    END IF;

                    IF p_section_id IS NULL THEN
                        -- Inserting, but name is taken
                        IF v_is_deleted THEN
                            -- Reactivate (treated as Update)
                            v_section_id := v_existing_id;
                            
                            UPDATE "SectionMaster"
                            SET "Capacity" = p_capacity,
                                "RoomNumber" = p_room_number,
                                "IsActive" = p_is_active,
                                "IsDeleted" = FALSE, -- Reactivate
                                "UpdatedBy" = p_user_id,
                                "UpdatedAt" = CURRENT_TIMESTAMP
                            WHERE "SectionID" = v_section_id;
                        ELSE
                            RAISE EXCEPTION 'Section "%" already exists.', p_section_name;
                        END IF;
                    ELSE
                        -- Updating existing ID (which matches name owner) -> Proceed to Standard Update
                        v_section_id := p_section_id;
                        
                        UPDATE "SectionMaster"
                        SET "SectionName" = p_section_name,
                            "Capacity" = p_capacity,
                            "RoomNumber" = p_room_number,
                            "IsActive" = p_is_active,
                            "UpdatedBy" = p_user_id,
                            "UpdatedAt" = CURRENT_TIMESTAMP
                        WHERE "SectionID" = v_section_id;
                    END IF;
                    
                ELSE
                    -- Case B: Name does not exist -> Standard Insert or Update (Update name change)
                    IF p_section_id IS NULL THEN
                        -- Insert New
                        INSERT INTO "SectionMaster" (
                            "ClassID", "SectionName", "Capacity", "RoomNumber",
                            "IsActive", "CreatedBy", "CreatedAt", "IsDeleted"
                        ) VALUES (
                            p_class_id, p_section_name, p_capacity, p_room_number,
                            p_is_active, p_user_id, CURRENT_TIMESTAMP, FALSE
                        ) RETURNING "SectionMaster"."SectionID" INTO v_section_id;
                    ELSE
                        -- Update ID (Name change case)
                        UPDATE "SectionMaster"
                        SET "SectionName" = p_section_name,
                            "Capacity" = p_capacity,
                            "RoomNumber" = p_room_number,
                            "IsActive" = p_is_active,
                            "UpdatedBy" = p_user_id,
                            "UpdatedAt" = CURRENT_TIMESTAMP
                        WHERE "SectionID" = p_section_id AND "IsDeleted" IS FALSE
                        RETURNING "SectionMaster"."SectionID" INTO v_section_id;
                    END IF;
                END IF;

                -- Return Result
                -- Uses table alias 'sm' to avoid ambiguity
                RETURN QUERY SELECT sm."SectionID", sm."ClassID", sm."SectionName"
                FROM "SectionMaster" sm WHERE sm."SectionID" = v_section_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            -- Keep fix
            """
        )
    ]
