# Generated by Django 5.0.14 on 2026-03-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_fix_proc_section_set_ambiguous_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeMaster',
            fields=[
                ('theme_id', models.AutoField(db_column='ThemeID', primary_key=True, serialize=False)),
                ('theme_name', models.CharField(db_column='ThemeName', max_length=100)),
                ('theme_key', models.CharField(db_column='ThemeKey', max_length=50)),
                ('primary_color', models.CharField(db_column='PrimaryColor', max_length=20)),
                ('primary_hover', models.CharField(db_column='PrimaryHover', max_length=20)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('display_order', models.IntegerField(db_column='DisplayOrder', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'ThemeMaster',
                'managed': False,
            },
        ),
    ]
