# Generated by Django 5.0.14 on 2026-04-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_create_brand_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('profile_id', models.AutoField(db_column='ProfileID', primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_column='BrandName', max_length=100)),
                ('brand_logo', models.BinaryField(blank=True, db_column='BrandLogo', null=True)),
                ('tagline', models.CharField(blank=True, db_column='Tagline', max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, db_column='GSTIN', max_length=15, null=True)),
                ('pan', models.CharField(blank=True, db_column='PAN', max_length=10, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, db_column='StateCode', max_length=5, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=100, null=True)),
                ('authorized_signature', models.BinaryField(blank=True, db_column='AuthorizedSignature', null=True)),
                ('authorized_signatory', models.CharField(blank=True, db_column='AuthorizedSignatory', max_length=100, null=True)),
                ('organization_stamp', models.BinaryField(blank=True, db_column='OrganizationStamp', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'db_table': 'BrandProfile',
                'managed': False,
            },
        ),
    ]
