-- BrandProfile Migration: Future Ready Standard Columns
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "Tagline" VARCHAR(255);
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "PAN" VARCHAR(10);
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "State" VARCHAR(100);
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "StateCode" VARCHAR(5);
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "BankName" VARCHAR(100);
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "AccountNo" VARCHAR(50);
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "IFSC" VARCHAR(20);
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "Branch" VARCHAR(100);
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "AuthorizedSignatory" VARCHAR(100);
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "CreatedBy" INTEGER;
ALTER TABLE "BrandProfile" ADD COLUMN IF NOT EXISTS "UpdatedBy" INTEGER;
