-- PostgreSQL function for creating schools
-- SchoolMaster has all fields including BoardID, MediumID, Principal/Director
-- SchoolCode is generated automatically by the database

CREATE OR REPLACE FUNCTION "Proc_CreateSchool_Set"(
    p_SchoolName VARCHAR,
    p_RegistrationNumber VARCHAR,
    p_Address TEXT,
    p_District INT,
    p_State INT,
    p_Country INT,
    p_Pincode VARCHAR,
    p_Phone VARCHAR,
    p_Email VARCHAR,
    p_Website VARCHAR,
    p_CreatedBy INT,
    p_SchoolLogo BYTEA,
    p_BoardID INT,
    p_MediumID INT,
    p_PrincipalName VARCHAR,
    p_PrincipalContactMail VARCHAR,
    p_PrincipalContactPhone VARCHAR,
    p_DirectorName VARCHAR,
    p_DirectorContactPhone VARCHAR,
    p_DirectorContactEmail VARCHAR,
    p_EstablishDate DATE
) RETURNS TABLE (
    "Ret_SchoolCode" VARCHAR,
    "Ret_Status" VARCHAR
) AS $$
DECLARE
    v_SchoolCode VARCHAR(20);
    v_SchoolID INT;
BEGIN
    -- Insert school (SchoolCode is auto-generated by DB)
    INSERT INTO "SchoolMaster" (
        "SchoolName", "RegistrationNumber", "Address",
        "District", "State", "Country", "Pincode", "Phone", "Email",
        "Website", "SchoolLogo", "BoardID", "MediumID",
        "PrincipalName", "PrincipalContactMail", "PrincipalContactPhone",
        "DirectorName", "DirectorContactPhone", "DirectorContactEmail",
        "EstablishDate", "CreatedBy", "CreatedAt", "IsDeleted"
    ) VALUES (
        p_SchoolName, p_RegistrationNumber, p_Address,
        p_District, p_State, p_Country, 
        p_Pincode, p_Phone, p_Email, p_Website, p_SchoolLogo,
        p_BoardID, p_MediumID, p_PrincipalName, p_PrincipalContactMail,
        p_PrincipalContactPhone, p_DirectorName, p_DirectorContactPhone,
        p_DirectorContactEmail, p_EstablishDate, p_CreatedBy, 
        CURRENT_TIMESTAMP, FALSE
    )
    RETURNING "SchoolID" INTO v_SchoolID;
    
    -- Get the generated SchoolCode (qualified to avoid ambiguity)
    SELECT sm."SchoolCode" INTO v_SchoolCode 
    FROM "SchoolMaster" sm 
    WHERE sm."SchoolID" = v_SchoolID;
    
    -- Return result
    RETURN QUERY SELECT 
        v_SchoolCode::VARCHAR AS "Ret_SchoolCode",
        ('School created successfully with code: ' || v_SchoolCode)::VARCHAR AS "Ret_Status";
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN QUERY SELECT 
            NULL::VARCHAR AS "Ret_SchoolCode",
            ('Error: ' || SQLERRM)::VARCHAR AS "Ret_Status";
END;
$$ LANGUAGE plpgsql;
