-- Table to store draft registration data from home page
CREATE TABLE RegistrationDraft (
    DraftID INT IDENTITY(1,1) PRIMARY KEY,
    SchoolName NVARCHAR(200),
    RegistrationNumber NVARCHAR(100),
    Address NVARCHAR(500),
    CountryID INT,
    StateID INT,
    DistrictID INT,
    Pincode NVARCHAR(10),
    Phone NVARCHAR(20),
    Email NVARCHAR(100),
    Website NVARCHAR(200),
    BoardID INT,
    MediumID INT,
    EstablishDate DATE,
    PrincipalName NVARCHAR(100),
    PrincipalEmail NVARCHAR(100),
    PrincipalPhone NVARCHAR(20),
    DirectorName NVARCHAR(100),
    DirectorEmail NVARCHAR(100),
    DirectorPhone NVARCHAR(20),
    PlanID INT,
    SubscriptionStartDate DATE,
    Status NVARCHAR(20) DEFAULT 'Pending',
    CreatedDate DATETIME DEFAULT GETDATE(),
    IsProcessed BIT DEFAULT 0
);
