# ShikshaWave/settings.py (verified) - global spacing fix applied successfully
# Triggering server reload...

"""
Django settings for ShikshaWave project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@kz55+rxc1$^9j$5xom64#8@3sq(r%*kw#b^g1f)8i5oj2-dfa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Force custom error pages even in debug mode
DEBUG_PROPAGATE_EXCEPTIONS = True

ALLOWED_HOSTS = ['shikshawave.in', 'www.shikshawave.in', '127.0.0.1', 'localhost', '0.0.0.0']
# Application definition
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'mail',
    'tickets',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'core.middleware.CustomAuthenticationMiddleware',
    'core.middleware.URLEncryptionMiddleware',
    'core.middleware.EncryptContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ErrorPageMiddleware',
    'core.middleware.SessionCleanupMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'ShikshaWave.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'core', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_user_context',
                'core.context_processors.menu_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShikshaWave.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ShikshaWave_Dev',
        'USER': 'postgres',
        'PASSWORD': 'AK&gs@06012025!',  # User should update this
        'HOST': 'localhost',
        'PORT': '5432',
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
    }
}

# Cache configuration for session management
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = False

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom login URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Email settings google mail
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'shikshawaves@gmail.com'
#EMAIL_HOST_PASSWORD = 'deon bwdb wwum imhj'
#DEFAULT_FROM_EMAIL = 'ShikshaWave <shikshawaves@gmail.com>'
#EMAIL_USE_SSL = False


# Dynamically loaded SMTP via Database
EMAIL_BACKEND = "mail.backend.DynamicEmailBackend"

# Hardcoded settings removed in favor of SMTPConfiguration table
# EMAIL_HOST = "smtp.hostinger.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "no-reply@shikshawave.in"
# EMAIL_HOST_PASSWORD = "AK&gs@29122025!#"
DEFAULT_FROM_EMAIL = "no-reply@shikshawave.in"
SERVER_EMAIL = "no-reply@shikshawave.in"

# Session settings
SESSION_COOKIE_AGE = 3600
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_NAME = 'shikshawave_sessionid'

#ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "shikshawave.in",
]
# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000', 
    'http://127.0.0.1:8000',
    'http://localhost',
    'http://127.0.0.1',
    "https://shikshawave.in"
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
 
 
 

