# Generated by Django 5.2.5 on 2025-08-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=100)),
                ('school_id', models.IntegerField(blank=True, db_column='SchoolId', null=True)),
                ('language', models.CharField(db_column='Language', default='en', max_length=10)),
                ('subject_template', models.TextField(db_column='SubjectTemplate')),
                ('body_text_template', models.TextField(blank=True, db_column='BodyTextTemplate', null=True)),
                ('body_html_template', models.TextField(blank=True, db_column='BodyHtmlTemplate', null=True)),
                ('default_from', models.CharField(blank=True, db_column='DefaultFrom', max_length=255, null=True)),
                ('cc', models.TextField(blank=True, db_column='Cc', null=True)),
                ('bcc', models.TextField(blank=True, db_column='Bcc', null=True)),
                ('placeholders', models.TextField(blank=True, db_column='Placeholders', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'EmailTemplate',
                'managed': False,
            },
        ),
    ]
