# Generated by Django 5.2.5 on 2025-11-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('email_tracking_id', models.AutoField(db_column='EmailTrackingID', primary_key=True, serialize=False)),
                ('email_code', models.CharField(db_column='EmailCode', max_length=100)),
                ('to_email', models.CharField(db_column='ToEmail', max_length=500)),
                ('from_email', models.CharField(db_column='FromEmail', max_length=255, null=True)),
                ('subject', models.TextField(db_column='Subject', null=True)),
                ('school_id', models.IntegerField(db_column='SchoolID', null=True)),
                ('email_body', models.TextField(db_column='EmailBody', null=True)),
                ('email_html_body', models.TextField(db_column='EmailHtmlBody', null=True)),
                ('placeholders', models.TextField(db_column='Placeholders', null=True)),
                ('has_attachments', models.BooleanField(db_column='HasAttachments', default=False)),
                ('attachment_count', models.IntegerField(db_column='AttachmentCount', default=0)),
                ('attachment_details', models.TextField(db_column='AttachmentDetails', null=True)),
                ('status', models.CharField(db_column='Status', default='Pending', max_length=50)),
                ('attempt_count', models.IntegerField(db_column='AttemptCount', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('completed_at', models.DateTimeField(db_column='CompletedAt', null=True)),
                ('last_error', models.TextField(db_column='LastError', null=True)),
            ],
            options={
                'db_table': 'EmailTracking',
                'managed': False,
            },
        ),
    ]
